begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  username text not null unique,
  bio text not null default '',
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_auth_user_changed()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, username, bio, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(
      new.raw_user_meta_data ->> 'username',
      split_part(new.email, '@', 1),
      'media-fan'
    ),
    coalesce(new.raw_user_meta_data ->> 'bio', ''),
    nullif(new.raw_user_meta_data ->> 'avatar_url', '')
  )
  on conflict (id) do update
  set email = excluded.email;

  return new;
end;
$$;

drop trigger if exists on_auth_user_changed on auth.users;
create trigger on_auth_user_changed
after insert or update on auth.users
for each row
execute function public.handle_auth_user_changed();

create table if not exists public.movies (
  id bigint generated by default as identity primary key,
  title text not null,
  year integer,
  genre text,
  director text,
  writers text,
  cast_members text,
  age_rating text,
  overview text,
  synopsis text,
  poster_url text,
  source_key text,
  created_at timestamptz not null default now()
);

create table if not exists public.tv_shows (
  id bigint generated by default as identity primary key,
  title text not null,
  year integer,
  genre text,
  creator text,
  writers text,
  cast_members text,
  age_rating text,
  overview text,
  synopsis text,
  poster_url text,
  seasons integer,
  source_key text,
  created_at timestamptz not null default now()
);

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text,
  year integer,
  genre text,
  synopsis text,
  cover_url text,
  source_key text,
  created_at timestamptz not null default now()
);

create table if not exists public.movie_ratings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  media_id bigint not null,
  acting integer not null check (acting between 1 and 5),
  writing integer not null check (writing between 1 and 5),
  originality integer not null check (originality between 1 and 5),
  pacing integer not null check (pacing between 1 and 5),
  cinematography integer not null check (cinematography between 1 and 5),
  review text,
  created_at timestamptz not null default now(),
  unique (user_id, media_id)
);

create table if not exists public.tv_show_ratings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  media_id bigint not null,
  premise integer not null check (premise between 1 and 5),
  originality integer not null check (originality between 1 and 5),
  acting integer not null check (acting between 1 and 6),
  cinematography integer not null check (cinematography between 1 and 5),
  writing integer not null check (writing between 1 and 6),
  pacing integer not null check (pacing between 1 and 5),
  resonance integer not null check (resonance between 1 and 6),
  review text,
  created_at timestamptz not null default now(),
  unique (user_id, media_id)
);

create table if not exists public.book_ratings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  media_id bigint not null,
  prose integer not null check (prose between 1 and 5),
  plot integer not null check (plot between 1 and 5),
  characters integer not null check (characters between 1 and 6),
  originality integer not null check (originality between 1 and 5),
  pacing integer not null check (pacing between 1 and 5),
  resonance integer not null check (resonance between 1 and 6),
  review text,
  created_at timestamptz not null default now(),
  unique (user_id, media_id)
);

create table if not exists public.watchlist (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  media_type text not null check (media_type in ('movie', 'tv_show', 'book')),
  media_id bigint not null,
  status text not null default 'plan_to_watch' check (
    status in ('plan_to_watch', 'watching', 'watched', 'plan_to_read', 'reading', 'read')
  ),
  added_at timestamptz not null default now(),
  unique (user_id, media_type, media_id)
);

create table if not exists public.media_lists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  share_code text not null unique,
  is_public boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.media_list_items (
  id bigint generated by default as identity primary key,
  list_id bigint not null references public.media_lists(id) on delete cascade,
  media_type text not null check (media_type in ('movie', 'tv_show', 'book')),
  media_id bigint not null,
  position integer not null default 0,
  added_at timestamptz not null default now(),
  unique (list_id, media_type, media_id)
);

create table if not exists public.media_list_collaborators (
  id bigint generated by default as identity primary key,
  list_id bigint not null references public.media_lists(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  invited_by_user_id uuid not null references auth.users(id) on delete cascade,
  added_at timestamptz not null default now(),
  unique (list_id, user_id)
);

create table if not exists public.media_list_votes (
  id bigint generated by default as identity primary key,
  list_item_id bigint not null references public.media_list_items(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  value integer not null check (value in (-1, 1)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (list_item_id, user_id)
);

create table if not exists public.chat_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  query text not null,
  intent text,
  response_length integer,
  sources_count integer,
  latency_ms integer,
  created_at timestamptz not null default now()
);

create table if not exists public.media_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  media_type text not null check (media_type in ('movie', 'tv_show', 'book')),
  year integer,
  reason text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_movies_source_key on public.movies(source_key);
create index if not exists idx_tv_shows_source_key on public.tv_shows(source_key);
create index if not exists idx_books_source_key on public.books(source_key);
create index if not exists idx_movie_ratings_user_id on public.movie_ratings(user_id);
create index if not exists idx_tv_show_ratings_user_id on public.tv_show_ratings(user_id);
create index if not exists idx_book_ratings_user_id on public.book_ratings(user_id);
create index if not exists idx_watchlist_user_id on public.watchlist(user_id);
create index if not exists idx_watchlist_user_media on public.watchlist(user_id, media_type, status);
create index if not exists idx_media_lists_user_id on public.media_lists(user_id);
create index if not exists idx_media_lists_share_code on public.media_lists(share_code);
create index if not exists idx_media_list_items_list_id on public.media_list_items(list_id);
create index if not exists idx_media_list_items_list_position on public.media_list_items(list_id, position);
create index if not exists idx_media_list_collaborators_list_id on public.media_list_collaborators(list_id);
create index if not exists idx_media_list_collaborators_user_id on public.media_list_collaborators(user_id);
create index if not exists idx_media_list_votes_item_id on public.media_list_votes(list_item_id);
create index if not exists idx_media_list_votes_user_id on public.media_list_votes(user_id);
create index if not exists idx_chat_logs_user_id on public.chat_logs(user_id);
create index if not exists idx_media_requests_user_id on public.media_requests(user_id);
create index if not exists idx_media_requests_status on public.media_requests(status);

drop trigger if exists trg_profiles_set_updated_at on public.profiles;
create trigger trg_profiles_set_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop trigger if exists trg_media_lists_set_updated_at on public.media_lists;
create trigger trg_media_lists_set_updated_at
before update on public.media_lists
for each row
execute function public.set_updated_at();

drop trigger if exists trg_media_list_votes_set_updated_at on public.media_list_votes;
create trigger trg_media_list_votes_set_updated_at
before update on public.media_list_votes
for each row
execute function public.set_updated_at();

drop trigger if exists trg_media_requests_set_updated_at on public.media_requests;
create trigger trg_media_requests_set_updated_at
before update on public.media_requests
for each row
execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.movies enable row level security;
alter table public.tv_shows enable row level security;
alter table public.books enable row level security;
alter table public.movie_ratings enable row level security;
alter table public.tv_show_ratings enable row level security;
alter table public.book_ratings enable row level security;
alter table public.watchlist enable row level security;
alter table public.todos enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "movies_public_read" on public.movies;
create policy "movies_public_read"
on public.movies
for select
using (true);

drop policy if exists "tv_public_read" on public.tv_shows;
create policy "tv_public_read"
on public.tv_shows
for select
using (true);

drop policy if exists "books_public_read" on public.books;
create policy "books_public_read"
on public.books
for select
using (true);

drop policy if exists "movie_ratings_select_own" on public.movie_ratings;
create policy "movie_ratings_select_own"
on public.movie_ratings
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "movie_ratings_insert_own" on public.movie_ratings;
create policy "movie_ratings_insert_own"
on public.movie_ratings
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "movie_ratings_update_own" on public.movie_ratings;
create policy "movie_ratings_update_own"
on public.movie_ratings
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "movie_ratings_delete_own" on public.movie_ratings;
create policy "movie_ratings_delete_own"
on public.movie_ratings
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "tv_show_ratings_select_own" on public.tv_show_ratings;
create policy "tv_show_ratings_select_own"
on public.tv_show_ratings
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "tv_show_ratings_insert_own" on public.tv_show_ratings;
create policy "tv_show_ratings_insert_own"
on public.tv_show_ratings
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "tv_show_ratings_update_own" on public.tv_show_ratings;
create policy "tv_show_ratings_update_own"
on public.tv_show_ratings
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "tv_show_ratings_delete_own" on public.tv_show_ratings;
create policy "tv_show_ratings_delete_own"
on public.tv_show_ratings
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "book_ratings_select_own" on public.book_ratings;
create policy "book_ratings_select_own"
on public.book_ratings
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "book_ratings_insert_own" on public.book_ratings;
create policy "book_ratings_insert_own"
on public.book_ratings
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "book_ratings_update_own" on public.book_ratings;
create policy "book_ratings_update_own"
on public.book_ratings
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "book_ratings_delete_own" on public.book_ratings;
create policy "book_ratings_delete_own"
on public.book_ratings
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "watchlist_select_own" on public.watchlist;
create policy "watchlist_select_own"
on public.watchlist
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "watchlist_insert_own" on public.watchlist;
create policy "watchlist_insert_own"
on public.watchlist
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "watchlist_update_own" on public.watchlist;
create policy "watchlist_update_own"
on public.watchlist
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "watchlist_delete_own" on public.watchlist;
create policy "watchlist_delete_own"
on public.watchlist
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "todos_public_read" on public.todos;
create policy "todos_public_read"
on public.todos
for select
using (true);

commit;
