#!/bin/sh
# Builds Config/Secrets.xcconfig from the repo's .env (the same public
# Supabase + TMDB keys the website uses). Usage: tv-apple/scripts/make-secrets.sh [site-url]
set -e
here="$(cd "$(dirname "$0")/.." && pwd)"
env_file="$here/../.env"
[ -f "$env_file" ] || { echo "No .env at $env_file" >&2; exit 1; }

value() { grep -E "^$1=" "$env_file" | tail -n 1 | cut -d= -f2- | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//"; }
# xcconfig reads "//" as the start of a comment.
escape_url() { printf '%s' "$1" | sed 's#//#/$()/#'; }

url="$(value REACT_APP_SUPABASE_URL)"
key="$(value REACT_APP_SUPABASE_PUBLISHABLE_KEY)"
[ -n "$key" ] || key="$(value REACT_APP_SUPABASE_ANON_KEY)"
tmdb="$(value REACT_APP_TMDB_API_KEY)"
site="${1:-https://binge-26.vercel.app}"

[ -n "$url" ] && [ -n "$key" ] || { echo "REACT_APP_SUPABASE_URL / _PUBLISHABLE_KEY missing from .env" >&2; exit 1; }

cat > "$here/Config/Secrets.xcconfig" <<CONF
// Generated by scripts/make-secrets.sh — do not commit.
BINGE_SUPABASE_URL = $(escape_url "$url")
BINGE_SUPABASE_KEY = $key
BINGE_TMDB_KEY = $tmdb
BINGE_SITE_URL = $(escape_url "$site")
CONF
echo "Wrote Config/Secrets.xcconfig (site: $site)"
