#!/bin/sh
# Finds the Apple ID team you added in Xcode (Settings → Accounts) and writes
# Config/Signing.xcconfig, so you never have to touch Signing & Capabilities.
#   scripts/setup-signing.sh          free Apple ID (Top Shelf shows Trending)
#   scripts/setup-signing.sh --paid   paid developer account (adds App Groups,
#                                     so Top Shelf shows your Continue Watching)
set -e
here="$(cd "$(dirname "$0")/.." && pwd)"
paid=0; [ "$1" = "--paid" ] && paid=1

team_info="$(defaults export com.apple.dt.Xcode - 2>/dev/null | python3 -c '
import plistlib, sys
try:
    prefs = plistlib.loads(sys.stdin.buffer.read())
except Exception:
    sys.exit(0)
teams = []
for key in ("IDEProvisioningTeamByIdentifier", "IDEProvisioningTeams"):
    for account, entries in (prefs.get(key) or {}).items():
        for team in entries if isinstance(entries, list) else [entries]:
            if isinstance(team, dict) and team.get("teamID"):
                teams.append((0 if team.get("isFreeProvisioningTeam") else 1, team["teamID"], team.get("teamName", ""), account))
teams.sort(reverse=True)
if teams:
    paid, team_id, name, account = teams[0]
    print(team_id, account, "paid" if paid else "free", name)
')"

if [ -z "$team_info" ]; then
  echo "No Apple ID found in Xcode yet."
  echo "Open Xcode → Settings (⌘,) → Accounts → + → Apple ID, sign in, then run this again."
  exit 1
fi

team="$(echo "$team_info" | cut -d' ' -f1)"
account="$(echo "$team_info" | cut -d' ' -f2)"
kind="$(echo "$team_info" | cut -d' ' -f3)"
# A bundle id nobody else has: com.<your apple id name>.binge (or your team id)
owner=""
case "$account" in *@*) owner="$(echo "$account" | cut -d@ -f1 | tr -cd 'A-Za-z0-9' | tr 'A-Z' 'a-z')" ;; esac
[ -n "$owner" ] || owner="$(echo "$team" | tr 'A-Z' 'a-z')"

{
  echo "// Generated by scripts/setup-signing.sh — do not commit."
  echo "BINGE_TEAM = $team"
  echo "BINGE_BUNDLE_ID = com.$owner.binge"
  if [ "$paid" = 1 ]; then
    echo "BINGE_APP_ENTITLEMENTS = Config/BingeTV.entitlements"
    echo "BINGE_SHELF_ENTITLEMENTS = Config/TopShelf.entitlements"
  fi
} > "$here/Config/Signing.xcconfig"

echo "Signing set up: team $team ($kind account), app id com.$owner.binge"
[ "$kind" = free ] && [ "$paid" = 1 ] && echo "Note: this looks like a free account; App Groups may be rejected. Re-run without --paid if signing fails."
exit 0
