


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pg_trgm" WITH SCHEMA "public";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."handle_auth_user_changed"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
begin
  insert into public.profiles (id, email, username, bio, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(
      new.raw_user_meta_data ->> 'username',
      split_part(new.email, '@', 1),
      'media-fan'
    ),
    coalesce(new.raw_user_meta_data ->> 'bio', ''),
    nullif(new.raw_user_meta_data ->> 'avatar_url', '')
  )
  on conflict (id) do update
  set
    email = excluded.email,
    username = coalesce(public.profiles.username, excluded.username),
    bio = coalesce(public.profiles.bio, excluded.bio),
    avatar_url = coalesce(public.profiles.avatar_url, excluded.avatar_url);

  return new;
end;
$$;


ALTER FUNCTION "public"."handle_auth_user_changed"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."set_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;


ALTER FUNCTION "public"."set_updated_at"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."books" (
    "id" smallint NOT NULL,
    "title" "text" NOT NULL,
    "author" "text",
    "year" integer,
    "genre" "text",
    "synopsis" "text",
    "cover_url" "text",
    "source_key" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "item_url" "text",
    "external_id" "text"
);


ALTER TABLE "public"."books" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."book_genres" AS
 SELECT DISTINCT TRIM(BOTH FROM "split_genre"."genre_value") AS "genre"
   FROM ("public"."books"
     CROSS JOIN LATERAL "regexp_split_to_table"(COALESCE("books"."genre", ''::"text"), ','::"text") "split_genre"("genre_value"))
  WHERE (TRIM(BOTH FROM "split_genre"."genre_value") <> ''::"text");


ALTER VIEW "public"."book_genres" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."book_ratings" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "media_id" bigint NOT NULL,
    "prose" integer NOT NULL,
    "plot" integer NOT NULL,
    "characters" integer NOT NULL,
    "originality" integer NOT NULL,
    "pacing" integer NOT NULL,
    "resonance" integer NOT NULL,
    "review" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "book_ratings_characters_check" CHECK ((("characters" >= 1) AND ("characters" <= 6))),
    CONSTRAINT "book_ratings_originality_check" CHECK ((("originality" >= 1) AND ("originality" <= 5))),
    CONSTRAINT "book_ratings_pacing_check" CHECK ((("pacing" >= 1) AND ("pacing" <= 5))),
    CONSTRAINT "book_ratings_plot_check" CHECK ((("plot" >= 1) AND ("plot" <= 5))),
    CONSTRAINT "book_ratings_prose_check" CHECK ((("prose" >= 1) AND ("prose" <= 5))),
    CONSTRAINT "book_ratings_resonance_check" CHECK ((("resonance" >= 1) AND ("resonance" <= 6)))
);


ALTER TABLE "public"."book_ratings" OWNER TO "postgres";


ALTER TABLE "public"."book_ratings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."book_ratings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."books" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."books_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."chat_logs" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "query" "text" NOT NULL,
    "intent" "text",
    "response_length" integer,
    "sources_count" integer,
    "latency_ms" integer,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."chat_logs" OWNER TO "postgres";


ALTER TABLE "public"."chat_logs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."chat_logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."episode_progress" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "media_id" bigint NOT NULL,
    "season" integer NOT NULL,
    "episode" integer NOT NULL,
    "watched_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."episode_progress" OWNER TO "postgres";


ALTER TABLE "public"."episode_progress" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."episode_progress_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."follows" (
    "id" bigint NOT NULL,
    "follower_id" "uuid" NOT NULL,
    "following_id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."follows" OWNER TO "postgres";


ALTER TABLE "public"."follows" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."follows_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."media_list_collaborators" (
    "id" bigint NOT NULL,
    "list_id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "invited_by_user_id" "uuid" NOT NULL,
    "added_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."media_list_collaborators" OWNER TO "postgres";


ALTER TABLE "public"."media_list_collaborators" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."media_list_collaborators_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."media_list_items" (
    "id" bigint NOT NULL,
    "list_id" bigint NOT NULL,
    "media_type" "text" NOT NULL,
    "media_id" bigint NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    "added_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "media_list_items_media_type_check" CHECK (("media_type" = ANY (ARRAY['movie'::"text", 'tv_show'::"text", 'book'::"text"])))
);


ALTER TABLE "public"."media_list_items" OWNER TO "postgres";


ALTER TABLE "public"."media_list_items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."media_list_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."media_list_votes" (
    "id" bigint NOT NULL,
    "list_item_id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "value" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "media_list_votes_value_check" CHECK (("value" = ANY (ARRAY['-1'::integer, 1])))
);


ALTER TABLE "public"."media_list_votes" OWNER TO "postgres";


ALTER TABLE "public"."media_list_votes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."media_list_votes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."media_lists" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "share_code" "text" NOT NULL,
    "is_public" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."media_lists" OWNER TO "postgres";


ALTER TABLE "public"."media_lists" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."media_lists_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."media_requests" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "media_type" "text" NOT NULL,
    "year" integer,
    "reason" "text",
    "status" "text" DEFAULT 'pending'::"text" NOT NULL,
    "admin_note" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "media_requests_media_type_check" CHECK (("media_type" = ANY (ARRAY['movie'::"text", 'tv_show'::"text", 'book'::"text"]))),
    CONSTRAINT "media_requests_status_check" CHECK (("status" = ANY (ARRAY['pending'::"text", 'approved'::"text", 'rejected'::"text"])))
);


ALTER TABLE "public"."media_requests" OWNER TO "postgres";


ALTER TABLE "public"."media_requests" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."media_requests_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."movies" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "year" integer,
    "genre" "text",
    "director" "text",
    "writers" "text",
    "cast_members" "text",
    "age_rating" "text",
    "overview" "text",
    "synopsis" "text",
    "poster_url" "text",
    "source_key" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "external_id" "text"
);


ALTER TABLE "public"."movies" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."movie_genres" AS
 SELECT DISTINCT TRIM(BOTH FROM "split_genre"."genre_value") AS "genre"
   FROM ("public"."movies"
     CROSS JOIN LATERAL "regexp_split_to_table"(COALESCE("movies"."genre", ''::"text"), ','::"text") "split_genre"("genre_value"))
  WHERE (TRIM(BOTH FROM "split_genre"."genre_value") <> ''::"text");


ALTER VIEW "public"."movie_genres" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."movie_ratings" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "media_id" bigint NOT NULL,
    "acting" integer NOT NULL,
    "writing" integer NOT NULL,
    "originality" integer NOT NULL,
    "pacing" integer NOT NULL,
    "cinematography" integer NOT NULL,
    "review" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text",
    CONSTRAINT "movie_ratings_acting_check" CHECK ((("acting" >= 1) AND ("acting" <= 5))),
    CONSTRAINT "movie_ratings_cinematography_check" CHECK ((("cinematography" >= 1) AND ("cinematography" <= 5))),
    CONSTRAINT "movie_ratings_originality_check" CHECK ((("originality" >= 1) AND ("originality" <= 5))),
    CONSTRAINT "movie_ratings_pacing_check" CHECK ((("pacing" >= 1) AND ("pacing" <= 5))),
    CONSTRAINT "movie_ratings_writing_check" CHECK ((("writing" >= 1) AND ("writing" <= 5)))
);


ALTER TABLE "public"."movie_ratings" OWNER TO "postgres";


ALTER TABLE "public"."movie_ratings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."movie_ratings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."movies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."movies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "email" "text" NOT NULL,
    "username" "text" NOT NULL,
    "bio" "text" DEFAULT ''::"text" NOT NULL,
    "avatar_url" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."todos" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."todos" OWNER TO "postgres";


ALTER TABLE "public"."todos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."todos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tv_shows" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "year" integer,
    "genre" "text",
    "creator" "text",
    "writers" "text",
    "cast_members" "text",
    "age_rating" "text",
    "overview" "text",
    "synopsis" "text",
    "poster_url" "text",
    "seasons" integer,
    "source_key" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "external_id" "text"
);


ALTER TABLE "public"."tv_shows" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."tv_show_genres" AS
 SELECT DISTINCT TRIM(BOTH FROM "split_genre"."genre_value") AS "genre"
   FROM ("public"."tv_shows"
     CROSS JOIN LATERAL "regexp_split_to_table"(COALESCE("tv_shows"."genre", ''::"text"), ','::"text") "split_genre"("genre_value"))
  WHERE (TRIM(BOTH FROM "split_genre"."genre_value") <> ''::"text");


ALTER VIEW "public"."tv_show_genres" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tv_show_ratings" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "media_id" bigint NOT NULL,
    "premise" integer NOT NULL,
    "originality" integer NOT NULL,
    "acting" integer NOT NULL,
    "cinematography" integer NOT NULL,
    "writing" integer NOT NULL,
    "pacing" integer NOT NULL,
    "resonance" integer NOT NULL,
    "review" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "tv_show_ratings_acting_check" CHECK ((("acting" >= 1) AND ("acting" <= 6))),
    CONSTRAINT "tv_show_ratings_cinematography_check" CHECK ((("cinematography" >= 1) AND ("cinematography" <= 5))),
    CONSTRAINT "tv_show_ratings_originality_check" CHECK ((("originality" >= 1) AND ("originality" <= 5))),
    CONSTRAINT "tv_show_ratings_pacing_check" CHECK ((("pacing" >= 1) AND ("pacing" <= 5))),
    CONSTRAINT "tv_show_ratings_premise_check" CHECK ((("premise" >= 1) AND ("premise" <= 5))),
    CONSTRAINT "tv_show_ratings_resonance_check" CHECK ((("resonance" >= 1) AND ("resonance" <= 6))),
    CONSTRAINT "tv_show_ratings_writing_check" CHECK ((("writing" >= 1) AND ("writing" <= 6)))
);


ALTER TABLE "public"."tv_show_ratings" OWNER TO "postgres";


ALTER TABLE "public"."tv_show_ratings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tv_show_ratings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."tv_shows" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tv_shows_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."watchlist" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "media_type" "text" NOT NULL,
    "media_id" bigint NOT NULL,
    "status" "text" DEFAULT 'plan_to_watch'::"text" NOT NULL,
    "added_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "current_season" integer,
    "current_episode" integer,
    "current_page" integer,
    "current_chapter" "text",
    "notes" "text",
    "completed_at" timestamp with time zone,
    "updated_at" timestamp with time zone,
    CONSTRAINT "watchlist_media_type_check" CHECK (("media_type" = ANY (ARRAY['movie'::"text", 'tv_show'::"text", 'book'::"text"]))),
    CONSTRAINT "watchlist_status_check" CHECK (("status" = ANY (ARRAY['plan_to_watch'::"text", 'watching'::"text", 'watched'::"text", 'plan_to_read'::"text", 'reading'::"text", 'read'::"text"])))
);


ALTER TABLE "public"."watchlist" OWNER TO "postgres";


ALTER TABLE "public"."watchlist" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."watchlist_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."book_ratings"
    ADD CONSTRAINT "book_ratings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."book_ratings"
    ADD CONSTRAINT "book_ratings_user_id_media_id_key" UNIQUE ("user_id", "media_id");



ALTER TABLE ONLY "public"."books"
    ADD CONSTRAINT "books_external_id_key" UNIQUE ("external_id");



ALTER TABLE ONLY "public"."books"
    ADD CONSTRAINT "books_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."books"
    ADD CONSTRAINT "books_source_key_key" UNIQUE ("source_key");



ALTER TABLE ONLY "public"."chat_logs"
    ADD CONSTRAINT "chat_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."episode_progress"
    ADD CONSTRAINT "episode_progress_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."episode_progress"
    ADD CONSTRAINT "episode_progress_unique" UNIQUE ("user_id", "media_id", "season", "episode");



ALTER TABLE ONLY "public"."follows"
    ADD CONSTRAINT "follows_follower_id_following_id_key" UNIQUE ("follower_id", "following_id");



ALTER TABLE ONLY "public"."follows"
    ADD CONSTRAINT "follows_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."media_list_collaborators"
    ADD CONSTRAINT "media_list_collaborators_list_id_user_id_key" UNIQUE ("list_id", "user_id");



ALTER TABLE ONLY "public"."media_list_collaborators"
    ADD CONSTRAINT "media_list_collaborators_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."media_list_items"
    ADD CONSTRAINT "media_list_items_list_id_media_type_media_id_key" UNIQUE ("list_id", "media_type", "media_id");



ALTER TABLE ONLY "public"."media_list_items"
    ADD CONSTRAINT "media_list_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."media_list_votes"
    ADD CONSTRAINT "media_list_votes_list_item_id_user_id_key" UNIQUE ("list_item_id", "user_id");



ALTER TABLE ONLY "public"."media_list_votes"
    ADD CONSTRAINT "media_list_votes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."media_lists"
    ADD CONSTRAINT "media_lists_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."media_lists"
    ADD CONSTRAINT "media_lists_share_code_key" UNIQUE ("share_code");



ALTER TABLE ONLY "public"."media_requests"
    ADD CONSTRAINT "media_requests_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."movie_ratings"
    ADD CONSTRAINT "movie_ratings_movie_title_key" UNIQUE ("title");



ALTER TABLE ONLY "public"."movie_ratings"
    ADD CONSTRAINT "movie_ratings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."movie_ratings"
    ADD CONSTRAINT "movie_ratings_user_id_media_id_key" UNIQUE ("user_id", "media_id");



ALTER TABLE ONLY "public"."movies"
    ADD CONSTRAINT "movies_pkey" PRIMARY KEY ("id", "title");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."todos"
    ADD CONSTRAINT "todos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tv_show_ratings"
    ADD CONSTRAINT "tv_show_ratings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tv_show_ratings"
    ADD CONSTRAINT "tv_show_ratings_user_id_media_id_key" UNIQUE ("user_id", "media_id");



ALTER TABLE ONLY "public"."tv_shows"
    ADD CONSTRAINT "tv_shows_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."watchlist"
    ADD CONSTRAINT "watchlist_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."watchlist"
    ADD CONSTRAINT "watchlist_user_id_media_type_media_id_key" UNIQUE ("user_id", "media_type", "media_id");



CREATE UNIQUE INDEX "books_external_id_unique" ON "public"."books" USING "btree" ("external_id");



CREATE UNIQUE INDEX "books_source_key_unique" ON "public"."books" USING "btree" ("source_key");



CREATE INDEX "idx_book_ratings_user_id" ON "public"."book_ratings" USING "btree" ("user_id");



CREATE INDEX "idx_books_author_lower" ON "public"."books" USING "btree" ("lower"("author"));



CREATE INDEX "idx_books_author_trgm" ON "public"."books" USING "gin" ("author" "public"."gin_trgm_ops");



CREATE INDEX "idx_books_genre" ON "public"."books" USING "btree" ("genre");



CREATE INDEX "idx_books_genre_trgm" ON "public"."books" USING "gin" ("genre" "public"."gin_trgm_ops");



CREATE INDEX "idx_books_source_key" ON "public"."books" USING "btree" ("source_key");



CREATE UNIQUE INDEX "idx_books_source_key_unique" ON "public"."books" USING "btree" ("source_key") WHERE ("source_key" IS NOT NULL);



CREATE INDEX "idx_books_title_lower" ON "public"."books" USING "btree" ("lower"("title"));



CREATE INDEX "idx_books_title_trgm" ON "public"."books" USING "gin" ("title" "public"."gin_trgm_ops");



CREATE INDEX "idx_books_year" ON "public"."books" USING "btree" ("year");



CREATE INDEX "idx_chat_logs_user_id" ON "public"."chat_logs" USING "btree" ("user_id");



CREATE INDEX "idx_episode_progress_user_media" ON "public"."episode_progress" USING "btree" ("user_id", "media_id");



CREATE INDEX "idx_media_list_collaborators_list_id" ON "public"."media_list_collaborators" USING "btree" ("list_id");



CREATE INDEX "idx_media_list_collaborators_user_id" ON "public"."media_list_collaborators" USING "btree" ("user_id");



CREATE INDEX "idx_media_list_items_list_id" ON "public"."media_list_items" USING "btree" ("list_id");



CREATE INDEX "idx_media_list_items_list_position" ON "public"."media_list_items" USING "btree" ("list_id", "position");



CREATE INDEX "idx_media_list_votes_item_id" ON "public"."media_list_votes" USING "btree" ("list_item_id");



CREATE INDEX "idx_media_list_votes_user_id" ON "public"."media_list_votes" USING "btree" ("user_id");



CREATE INDEX "idx_media_lists_share_code" ON "public"."media_lists" USING "btree" ("share_code");



CREATE INDEX "idx_media_lists_user_id" ON "public"."media_lists" USING "btree" ("user_id");



CREATE INDEX "idx_media_requests_status" ON "public"."media_requests" USING "btree" ("status");



CREATE INDEX "idx_media_requests_user_id" ON "public"."media_requests" USING "btree" ("user_id");



CREATE INDEX "idx_movie_ratings_user_id" ON "public"."movie_ratings" USING "btree" ("user_id");



CREATE INDEX "idx_movies_genre" ON "public"."movies" USING "btree" ("genre");



CREATE INDEX "idx_movies_genre_trgm" ON "public"."movies" USING "gin" ("genre" "public"."gin_trgm_ops");



CREATE INDEX "idx_movies_source_key" ON "public"."movies" USING "btree" ("source_key");



CREATE UNIQUE INDEX "idx_movies_source_key_unique" ON "public"."movies" USING "btree" ("source_key") WHERE ("source_key" IS NOT NULL);



CREATE INDEX "idx_movies_title_lower" ON "public"."movies" USING "btree" ("lower"("title"));



CREATE INDEX "idx_movies_title_trgm" ON "public"."movies" USING "gin" ("title" "public"."gin_trgm_ops");



CREATE INDEX "idx_movies_year" ON "public"."movies" USING "btree" ("year");



CREATE INDEX "idx_tv_show_ratings_user_id" ON "public"."tv_show_ratings" USING "btree" ("user_id");



CREATE INDEX "idx_tv_shows_genre" ON "public"."tv_shows" USING "btree" ("genre");



CREATE INDEX "idx_tv_shows_genre_trgm" ON "public"."tv_shows" USING "gin" ("genre" "public"."gin_trgm_ops");



CREATE INDEX "idx_tv_shows_source_key" ON "public"."tv_shows" USING "btree" ("source_key");



CREATE UNIQUE INDEX "idx_tv_shows_source_key_unique" ON "public"."tv_shows" USING "btree" ("source_key") WHERE ("source_key" IS NOT NULL);



CREATE INDEX "idx_tv_shows_title_lower" ON "public"."tv_shows" USING "btree" ("lower"("title"));



CREATE INDEX "idx_tv_shows_title_trgm" ON "public"."tv_shows" USING "gin" ("title" "public"."gin_trgm_ops");



CREATE INDEX "idx_tv_shows_year" ON "public"."tv_shows" USING "btree" ("year");



CREATE INDEX "idx_watchlist_user_id" ON "public"."watchlist" USING "btree" ("user_id");



CREATE INDEX "idx_watchlist_user_media" ON "public"."watchlist" USING "btree" ("user_id", "media_type", "status");



CREATE UNIQUE INDEX "movies_external_id_key" ON "public"."movies" USING "btree" ("external_id") WHERE ("external_id" IS NOT NULL);



CREATE UNIQUE INDEX "movies_external_id_unique" ON "public"."movies" USING "btree" ("external_id");



CREATE UNIQUE INDEX "movies_source_key_unique" ON "public"."movies" USING "btree" ("source_key");



CREATE UNIQUE INDEX "tv_shows_external_id_key" ON "public"."tv_shows" USING "btree" ("external_id") WHERE ("external_id" IS NOT NULL);



CREATE UNIQUE INDEX "tv_shows_external_id_unique" ON "public"."tv_shows" USING "btree" ("external_id");



CREATE UNIQUE INDEX "tv_shows_source_key_unique" ON "public"."tv_shows" USING "btree" ("source_key");



CREATE OR REPLACE TRIGGER "trg_media_list_votes_set_updated_at" BEFORE UPDATE ON "public"."media_list_votes" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();



CREATE OR REPLACE TRIGGER "trg_media_lists_set_updated_at" BEFORE UPDATE ON "public"."media_lists" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();



CREATE OR REPLACE TRIGGER "trg_media_requests_set_updated_at" BEFORE UPDATE ON "public"."media_requests" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();



CREATE OR REPLACE TRIGGER "trg_profiles_set_updated_at" BEFORE UPDATE ON "public"."profiles" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();



ALTER TABLE ONLY "public"."book_ratings"
    ADD CONSTRAINT "book_ratings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."chat_logs"
    ADD CONSTRAINT "chat_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."episode_progress"
    ADD CONSTRAINT "episode_progress_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."follows"
    ADD CONSTRAINT "follows_follower_id_fkey" FOREIGN KEY ("follower_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."follows"
    ADD CONSTRAINT "follows_following_id_fkey" FOREIGN KEY ("following_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."media_list_collaborators"
    ADD CONSTRAINT "media_list_collaborators_invited_by_user_id_fkey" FOREIGN KEY ("invited_by_user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."media_list_collaborators"
    ADD CONSTRAINT "media_list_collaborators_list_id_fkey" FOREIGN KEY ("list_id") REFERENCES "public"."media_lists"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."media_list_collaborators"
    ADD CONSTRAINT "media_list_collaborators_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."media_list_items"
    ADD CONSTRAINT "media_list_items_list_id_fkey" FOREIGN KEY ("list_id") REFERENCES "public"."media_lists"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."media_list_votes"
    ADD CONSTRAINT "media_list_votes_list_item_id_fkey" FOREIGN KEY ("list_item_id") REFERENCES "public"."media_list_items"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."media_list_votes"
    ADD CONSTRAINT "media_list_votes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."media_lists"
    ADD CONSTRAINT "media_lists_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."media_requests"
    ADD CONSTRAINT "media_requests_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."movie_ratings"
    ADD CONSTRAINT "movie_ratings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."tv_show_ratings"
    ADD CONSTRAINT "tv_show_ratings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."watchlist"
    ADD CONSTRAINT "watchlist_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Users can manage their own episode progress" ON "public"."episode_progress" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."book_ratings" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "book_ratings_delete_own" ON "public"."book_ratings" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "book_ratings_insert_own" ON "public"."book_ratings" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "book_ratings_select_own" ON "public"."book_ratings" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "book_ratings_update_own" ON "public"."book_ratings" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."books" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "books_public_read" ON "public"."books" FOR SELECT USING (true);



ALTER TABLE "public"."chat_logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."episode_progress" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."follows" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "follows_delete" ON "public"."follows" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "follower_id"));



CREATE POLICY "follows_insert" ON "public"."follows" FOR INSERT TO "authenticated" WITH CHECK ((("auth"."uid"() = "follower_id") AND ("auth"."uid"() <> "following_id")));



CREATE POLICY "follows_select" ON "public"."follows" FOR SELECT TO "authenticated" USING ((("auth"."uid"() = "follower_id") OR ("auth"."uid"() = "following_id")));



ALTER TABLE "public"."media_list_collaborators" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."media_list_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."media_list_votes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."media_lists" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."media_requests" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."movie_ratings" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "movie_ratings_delete_own" ON "public"."movie_ratings" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "movie_ratings_insert_own" ON "public"."movie_ratings" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "movie_ratings_select_own" ON "public"."movie_ratings" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "movie_ratings_update_own" ON "public"."movie_ratings" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."movies" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "movies_public_read" ON "public"."movies" FOR SELECT USING (true);



ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "profiles_insert_own" ON "public"."profiles" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "id"));



CREATE POLICY "profiles_select_own" ON "public"."profiles" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "id"));



CREATE POLICY "profiles_update_own" ON "public"."profiles" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "id")) WITH CHECK (("auth"."uid"() = "id"));



ALTER TABLE "public"."todos" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "todos_public_read" ON "public"."todos" FOR SELECT USING (true);



CREATE POLICY "tv_public_read" ON "public"."tv_shows" FOR SELECT USING (true);



ALTER TABLE "public"."tv_show_ratings" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "tv_show_ratings_delete_own" ON "public"."tv_show_ratings" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "tv_show_ratings_insert_own" ON "public"."tv_show_ratings" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "tv_show_ratings_select_own" ON "public"."tv_show_ratings" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "tv_show_ratings_update_own" ON "public"."tv_show_ratings" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."tv_shows" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."watchlist" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "watchlist_delete_own" ON "public"."watchlist" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "watchlist_insert_own" ON "public"."watchlist" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "watchlist_select_own" ON "public"."watchlist" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "watchlist_update_own" ON "public"."watchlist" FOR UPDATE TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_in"("cstring") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_in"("cstring") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_in"("cstring") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_in"("cstring") TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_out"("public"."gtrgm") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_out"("public"."gtrgm") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_out"("public"."gtrgm") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_out"("public"."gtrgm") TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."gin_extract_query_trgm"("text", "internal", smallint, "internal", "internal", "internal", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gin_extract_query_trgm"("text", "internal", smallint, "internal", "internal", "internal", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gin_extract_query_trgm"("text", "internal", smallint, "internal", "internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gin_extract_query_trgm"("text", "internal", smallint, "internal", "internal", "internal", "internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gin_extract_value_trgm"("text", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gin_extract_value_trgm"("text", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gin_extract_value_trgm"("text", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gin_extract_value_trgm"("text", "internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gin_trgm_consistent"("internal", smallint, "text", integer, "internal", "internal", "internal", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gin_trgm_consistent"("internal", smallint, "text", integer, "internal", "internal", "internal", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gin_trgm_consistent"("internal", smallint, "text", integer, "internal", "internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gin_trgm_consistent"("internal", smallint, "text", integer, "internal", "internal", "internal", "internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gin_trgm_triconsistent"("internal", smallint, "text", integer, "internal", "internal", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gin_trgm_triconsistent"("internal", smallint, "text", integer, "internal", "internal", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gin_trgm_triconsistent"("internal", smallint, "text", integer, "internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gin_trgm_triconsistent"("internal", smallint, "text", integer, "internal", "internal", "internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_compress"("internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_compress"("internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_compress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_compress"("internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_consistent"("internal", "text", smallint, "oid", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_consistent"("internal", "text", smallint, "oid", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_consistent"("internal", "text", smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_consistent"("internal", "text", smallint, "oid", "internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_decompress"("internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_decompress"("internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_decompress"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_decompress"("internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_distance"("internal", "text", smallint, "oid", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_distance"("internal", "text", smallint, "oid", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_distance"("internal", "text", smallint, "oid", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_distance"("internal", "text", smallint, "oid", "internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_options"("internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_options"("internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_options"("internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_options"("internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_penalty"("internal", "internal", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_penalty"("internal", "internal", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_penalty"("internal", "internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_penalty"("internal", "internal", "internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_picksplit"("internal", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_picksplit"("internal", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_picksplit"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_picksplit"("internal", "internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_same"("public"."gtrgm", "public"."gtrgm", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_same"("public"."gtrgm", "public"."gtrgm", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_same"("public"."gtrgm", "public"."gtrgm", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_same"("public"."gtrgm", "public"."gtrgm", "internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."gtrgm_union"("internal", "internal") TO "postgres";
GRANT ALL ON FUNCTION "public"."gtrgm_union"("internal", "internal") TO "anon";
GRANT ALL ON FUNCTION "public"."gtrgm_union"("internal", "internal") TO "authenticated";
GRANT ALL ON FUNCTION "public"."gtrgm_union"("internal", "internal") TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_auth_user_changed"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_auth_user_changed"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_auth_user_changed"() TO "service_role";



GRANT ALL ON FUNCTION "public"."set_limit"(real) TO "postgres";
GRANT ALL ON FUNCTION "public"."set_limit"(real) TO "anon";
GRANT ALL ON FUNCTION "public"."set_limit"(real) TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_limit"(real) TO "service_role";



GRANT ALL ON FUNCTION "public"."set_updated_at"() TO "anon";
GRANT ALL ON FUNCTION "public"."set_updated_at"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_updated_at"() TO "service_role";



GRANT ALL ON FUNCTION "public"."show_limit"() TO "postgres";
GRANT ALL ON FUNCTION "public"."show_limit"() TO "anon";
GRANT ALL ON FUNCTION "public"."show_limit"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."show_limit"() TO "service_role";



GRANT ALL ON FUNCTION "public"."show_trgm"("text") TO "postgres";
GRANT ALL ON FUNCTION "public"."show_trgm"("text") TO "anon";
GRANT ALL ON FUNCTION "public"."show_trgm"("text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."show_trgm"("text") TO "service_role";



GRANT ALL ON FUNCTION "public"."similarity"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."similarity"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."similarity"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."similarity"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."similarity_dist"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."similarity_dist"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."similarity_dist"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."similarity_dist"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."similarity_op"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."similarity_op"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."similarity_op"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."similarity_op"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."strict_word_similarity"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."strict_word_similarity"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."strict_word_similarity"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."strict_word_similarity"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."strict_word_similarity_commutator_op"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_commutator_op"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_commutator_op"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_commutator_op"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."strict_word_similarity_dist_commutator_op"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_dist_commutator_op"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_dist_commutator_op"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_dist_commutator_op"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."strict_word_similarity_dist_op"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_dist_op"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_dist_op"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_dist_op"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."strict_word_similarity_op"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_op"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_op"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."strict_word_similarity_op"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."word_similarity"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."word_similarity"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."word_similarity"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."word_similarity"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."word_similarity_commutator_op"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."word_similarity_commutator_op"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."word_similarity_commutator_op"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."word_similarity_commutator_op"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."word_similarity_dist_commutator_op"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."word_similarity_dist_commutator_op"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."word_similarity_dist_commutator_op"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."word_similarity_dist_commutator_op"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."word_similarity_dist_op"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."word_similarity_dist_op"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."word_similarity_dist_op"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."word_similarity_dist_op"("text", "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."word_similarity_op"("text", "text") TO "postgres";
GRANT ALL ON FUNCTION "public"."word_similarity_op"("text", "text") TO "anon";
GRANT ALL ON FUNCTION "public"."word_similarity_op"("text", "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."word_similarity_op"("text", "text") TO "service_role";


















GRANT ALL ON TABLE "public"."books" TO "anon";
GRANT ALL ON TABLE "public"."books" TO "authenticated";
GRANT ALL ON TABLE "public"."books" TO "service_role";



GRANT ALL ON TABLE "public"."book_genres" TO "anon";
GRANT ALL ON TABLE "public"."book_genres" TO "authenticated";
GRANT ALL ON TABLE "public"."book_genres" TO "service_role";



GRANT ALL ON TABLE "public"."book_ratings" TO "anon";
GRANT ALL ON TABLE "public"."book_ratings" TO "authenticated";
GRANT ALL ON TABLE "public"."book_ratings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."book_ratings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."book_ratings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."book_ratings_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."books_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."books_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."books_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."chat_logs" TO "anon";
GRANT ALL ON TABLE "public"."chat_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."chat_logs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."chat_logs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."chat_logs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."chat_logs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."episode_progress" TO "anon";
GRANT ALL ON TABLE "public"."episode_progress" TO "authenticated";
GRANT ALL ON TABLE "public"."episode_progress" TO "service_role";



GRANT ALL ON SEQUENCE "public"."episode_progress_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."episode_progress_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."episode_progress_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."follows" TO "anon";
GRANT ALL ON TABLE "public"."follows" TO "authenticated";
GRANT ALL ON TABLE "public"."follows" TO "service_role";



GRANT ALL ON SEQUENCE "public"."follows_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."follows_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."follows_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."media_list_collaborators" TO "anon";
GRANT ALL ON TABLE "public"."media_list_collaborators" TO "authenticated";
GRANT ALL ON TABLE "public"."media_list_collaborators" TO "service_role";



GRANT ALL ON SEQUENCE "public"."media_list_collaborators_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."media_list_collaborators_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."media_list_collaborators_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."media_list_items" TO "anon";
GRANT ALL ON TABLE "public"."media_list_items" TO "authenticated";
GRANT ALL ON TABLE "public"."media_list_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."media_list_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."media_list_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."media_list_items_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."media_list_votes" TO "anon";
GRANT ALL ON TABLE "public"."media_list_votes" TO "authenticated";
GRANT ALL ON TABLE "public"."media_list_votes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."media_list_votes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."media_list_votes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."media_list_votes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."media_lists" TO "anon";
GRANT ALL ON TABLE "public"."media_lists" TO "authenticated";
GRANT ALL ON TABLE "public"."media_lists" TO "service_role";



GRANT ALL ON SEQUENCE "public"."media_lists_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."media_lists_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."media_lists_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."media_requests" TO "anon";
GRANT ALL ON TABLE "public"."media_requests" TO "authenticated";
GRANT ALL ON TABLE "public"."media_requests" TO "service_role";



GRANT ALL ON SEQUENCE "public"."media_requests_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."media_requests_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."media_requests_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."movies" TO "anon";
GRANT ALL ON TABLE "public"."movies" TO "authenticated";
GRANT ALL ON TABLE "public"."movies" TO "service_role";



GRANT ALL ON TABLE "public"."movie_genres" TO "anon";
GRANT ALL ON TABLE "public"."movie_genres" TO "authenticated";
GRANT ALL ON TABLE "public"."movie_genres" TO "service_role";



GRANT ALL ON TABLE "public"."movie_ratings" TO "anon";
GRANT ALL ON TABLE "public"."movie_ratings" TO "authenticated";
GRANT ALL ON TABLE "public"."movie_ratings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."movie_ratings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."movie_ratings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."movie_ratings_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."movies_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."movies_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."movies_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."todos" TO "anon";
GRANT ALL ON TABLE "public"."todos" TO "authenticated";
GRANT ALL ON TABLE "public"."todos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."todos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."todos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."todos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tv_shows" TO "anon";
GRANT ALL ON TABLE "public"."tv_shows" TO "authenticated";
GRANT ALL ON TABLE "public"."tv_shows" TO "service_role";



GRANT ALL ON TABLE "public"."tv_show_genres" TO "anon";
GRANT ALL ON TABLE "public"."tv_show_genres" TO "authenticated";
GRANT ALL ON TABLE "public"."tv_show_genres" TO "service_role";



GRANT ALL ON TABLE "public"."tv_show_ratings" TO "anon";
GRANT ALL ON TABLE "public"."tv_show_ratings" TO "authenticated";
GRANT ALL ON TABLE "public"."tv_show_ratings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tv_show_ratings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tv_show_ratings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tv_show_ratings_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tv_shows_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tv_shows_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tv_shows_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."watchlist" TO "anon";
GRANT ALL ON TABLE "public"."watchlist" TO "authenticated";
GRANT ALL ON TABLE "public"."watchlist" TO "service_role";



GRANT ALL ON SEQUENCE "public"."watchlist_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."watchlist_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."watchlist_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

CREATE TRIGGER on_auth_user_changed AFTER INSERT OR UPDATE ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_auth_user_changed();


