-- Outside ratings cache, followed teams, and sports alerts.

-- ── 1. Outside ratings (IMDb / Rotten Tomatoes / Metacritic via OMDb) ──
-- OMDb's free tier is 1,000 requests a day, so every lookup is cached here
-- and shared by everyone (ratings aren't personal). Written by the server
-- with the service role; readable by anyone.
create table if not exists public.title_ratings (
  source_key text primary key,            -- 'tmdb:movie:123' / 'tmdb:tv:456'
  imdb_id text,
  imdb_rating numeric,
  imdb_votes integer,
  rotten_tomatoes integer,                -- percent
  metacritic integer,                     -- 0–100
  fetched_at timestamptz not null default now()
);
alter table public.title_ratings enable row level security;
drop policy if exists title_ratings_read on public.title_ratings;
create policy title_ratings_read on public.title_ratings for select using (true);

-- Per-season IMDb episode ratings for the episode heatmap.
create table if not exists public.episode_ratings_cache (
  imdb_id text not null,
  season integer not null,
  episodes jsonb not null,                -- [{ episode, title, rating, votes }]
  fetched_at timestamptz not null default now(),
  primary key (imdb_id, season)
);
alter table public.episode_ratings_cache enable row level security;
drop policy if exists episode_ratings_cache_read on public.episode_ratings_cache;
create policy episode_ratings_cache_read on public.episode_ratings_cache for select using (true);

-- ── 2. Followed teams ─────────────────────────────────────────────────
create table if not exists public.followed_teams (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  profile_id uuid references public.account_profiles(id) on delete cascade,
  league_path text not null,              -- ESPN path, e.g. 'basketball/nba'
  team_id text not null,                  -- ESPN team id
  team_name text not null,
  team_abbr text,
  logo text,
  alerts boolean not null default true,   -- close-game + game-start pushes
  created_at timestamptz not null default now()
);
create unique index if not exists idx_followed_teams_unique
  on public.followed_teams (user_id, coalesce(profile_id, '00000000-0000-0000-0000-000000000000'::uuid), league_path, team_id);
alter table public.followed_teams enable row level security;
drop policy if exists followed_teams_own on public.followed_teams;
create policy followed_teams_own on public.followed_teams
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ── 3. Sports alerts already sent (dedupe; written by the cron) ────────
create table if not exists public.game_alerts_sent (
  user_id uuid not null references auth.users(id) on delete cascade,
  event_id text not null,
  kind text not null,                     -- 'starting' | 'close' | 'overtime' | 'no_hitter'
  sent_at timestamptz not null default now(),
  primary key (user_id, event_id, kind)
);
alter table public.game_alerts_sent enable row level security;
drop policy if exists game_alerts_sent_read_own on public.game_alerts_sent;
create policy game_alerts_sent_read_own on public.game_alerts_sent for select using (user_id = auth.uid());
