alter table public.profiles enable row level security;

drop policy if exists "profiles_public_directory_read" on public.profiles;
create policy "profiles_public_directory_read"
on public.profiles
for select
using (coalesce(is_public, true) or auth.uid() = id);

create table if not exists public.chat_errors (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  error_type text,
  error_message text not null,
  created_at timestamp with time zone default now()
);

create index if not exists idx_chat_errors_created_at on public.chat_errors (created_at desc);
create index if not exists idx_chat_errors_user_id on public.chat_errors (user_id);

alter table public.chat_errors enable row level security;

drop policy if exists "chat_logs_admin_read" on public.chat_logs;
create policy "chat_logs_admin_read"
on public.chat_logs
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and coalesce(profiles.is_admin, false) = true
  )
);

drop policy if exists "chat_errors_admin_read" on public.chat_errors;
create policy "chat_errors_admin_read"
on public.chat_errors
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and coalesce(profiles.is_admin, false) = true
  )
);

grant select on public.chat_errors to authenticated;
grant all on public.chat_errors to service_role;
grant usage, select on sequence public.chat_errors_id_seq to authenticated;
grant all on sequence public.chat_errors_id_seq to service_role;
