drop extension if exists "pg_net";

create extension if not exists "pg_trgm" with schema "public";


  create table "public"."book_ratings" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "media_id" bigint not null,
    "prose" integer not null,
    "plot" integer not null,
    "characters" integer not null,
    "originality" integer not null,
    "pacing" integer not null,
    "resonance" integer not null,
    "review" text,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."book_ratings" enable row level security;


  create table "public"."books" (
    "id" smallint generated by default as identity not null,
    "title" text not null,
    "author" text,
    "year" integer,
    "genre" text,
    "synopsis" text,
    "cover_url" text,
    "source_key" text,
    "created_at" timestamp with time zone not null default now(),
    "item_url" text,
    "external_id" text
      );


alter table "public"."books" enable row level security;


  create table "public"."chat_logs" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "query" text not null,
    "intent" text,
    "response_length" integer,
    "sources_count" integer,
    "latency_ms" integer,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."chat_logs" enable row level security;


  create table "public"."media_list_collaborators" (
    "id" bigint generated by default as identity not null,
    "list_id" bigint not null,
    "user_id" uuid not null,
    "invited_by_user_id" uuid not null,
    "added_at" timestamp with time zone not null default now()
      );


alter table "public"."media_list_collaborators" enable row level security;


  create table "public"."media_list_items" (
    "id" bigint generated by default as identity not null,
    "list_id" bigint not null,
    "media_type" text not null,
    "media_id" bigint not null,
    "position" integer not null default 0,
    "added_at" timestamp with time zone not null default now()
      );


alter table "public"."media_list_items" enable row level security;


  create table "public"."media_list_votes" (
    "id" bigint generated by default as identity not null,
    "list_item_id" bigint not null,
    "user_id" uuid not null,
    "value" integer not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."media_list_votes" enable row level security;


  create table "public"."media_lists" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "name" text not null,
    "share_code" text not null,
    "is_public" boolean not null default false,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."media_lists" enable row level security;


  create table "public"."media_requests" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "title" text not null,
    "media_type" text not null,
    "year" integer,
    "reason" text,
    "status" text not null default 'pending'::text,
    "admin_note" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."media_requests" enable row level security;


  create table "public"."movie_ratings" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "media_id" bigint not null,
    "acting" integer not null,
    "writing" integer not null,
    "originality" integer not null,
    "pacing" integer not null,
    "cinematography" integer not null,
    "review" text,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."movie_ratings" enable row level security;


  create table "public"."movies" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "year" integer,
    "genre" text,
    "director" text,
    "writers" text,
    "cast_members" text,
    "age_rating" text,
    "overview" text,
    "synopsis" text,
    "poster_url" text,
    "source_key" text,
    "created_at" timestamp with time zone not null default now(),
    "external_id" text
      );


alter table "public"."movies" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "email" text not null,
    "username" text not null,
    "bio" text not null default ''::text,
    "avatar_url" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."profiles" enable row level security;


  create table "public"."todos" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."todos" enable row level security;


  create table "public"."tv_show_ratings" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "media_id" bigint not null,
    "premise" integer not null,
    "originality" integer not null,
    "acting" integer not null,
    "cinematography" integer not null,
    "writing" integer not null,
    "pacing" integer not null,
    "resonance" integer not null,
    "review" text,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."tv_show_ratings" enable row level security;


  create table "public"."tv_shows" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "year" integer,
    "genre" text,
    "creator" text,
    "writers" text,
    "cast_members" text,
    "age_rating" text,
    "overview" text,
    "synopsis" text,
    "poster_url" text,
    "seasons" integer,
    "source_key" text,
    "created_at" timestamp with time zone not null default now(),
    "external_id" text
      );


alter table "public"."tv_shows" enable row level security;


  create table "public"."watchlist" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "media_type" text not null,
    "media_id" bigint not null,
    "status" text not null default 'plan_to_watch'::text,
    "added_at" timestamp with time zone not null default now()
      );


alter table "public"."watchlist" enable row level security;

CREATE UNIQUE INDEX book_ratings_pkey ON public.book_ratings USING btree (id);

CREATE UNIQUE INDEX book_ratings_user_id_media_id_key ON public.book_ratings USING btree (user_id, media_id);

CREATE UNIQUE INDEX books_external_id_key ON public.books USING btree (external_id);

CREATE UNIQUE INDEX books_external_id_unique ON public.books USING btree (external_id);

CREATE UNIQUE INDEX books_pkey ON public.books USING btree (id);

CREATE UNIQUE INDEX books_source_key_key ON public.books USING btree (source_key);

CREATE UNIQUE INDEX books_source_key_unique ON public.books USING btree (source_key);

CREATE UNIQUE INDEX chat_logs_pkey ON public.chat_logs USING btree (id);

CREATE INDEX idx_book_ratings_user_id ON public.book_ratings USING btree (user_id);

CREATE INDEX idx_books_author_lower ON public.books USING btree (lower(author));

CREATE INDEX idx_books_author_trgm ON public.books USING gin (author public.gin_trgm_ops);

CREATE INDEX idx_books_genre ON public.books USING btree (genre);

CREATE INDEX idx_books_genre_trgm ON public.books USING gin (genre public.gin_trgm_ops);

CREATE INDEX idx_books_source_key ON public.books USING btree (source_key);

CREATE UNIQUE INDEX idx_books_source_key_unique ON public.books USING btree (source_key) WHERE (source_key IS NOT NULL);

CREATE INDEX idx_books_title_lower ON public.books USING btree (lower(title));

CREATE INDEX idx_books_title_trgm ON public.books USING gin (title public.gin_trgm_ops);

CREATE INDEX idx_books_year ON public.books USING btree (year);

CREATE INDEX idx_chat_logs_user_id ON public.chat_logs USING btree (user_id);

CREATE INDEX idx_media_list_collaborators_list_id ON public.media_list_collaborators USING btree (list_id);

CREATE INDEX idx_media_list_collaborators_user_id ON public.media_list_collaborators USING btree (user_id);

CREATE INDEX idx_media_list_items_list_id ON public.media_list_items USING btree (list_id);

CREATE INDEX idx_media_list_items_list_position ON public.media_list_items USING btree (list_id, "position");

CREATE INDEX idx_media_list_votes_item_id ON public.media_list_votes USING btree (list_item_id);

CREATE INDEX idx_media_list_votes_user_id ON public.media_list_votes USING btree (user_id);

CREATE INDEX idx_media_lists_share_code ON public.media_lists USING btree (share_code);

CREATE INDEX idx_media_lists_user_id ON public.media_lists USING btree (user_id);

CREATE INDEX idx_media_requests_status ON public.media_requests USING btree (status);

CREATE INDEX idx_media_requests_user_id ON public.media_requests USING btree (user_id);

CREATE INDEX idx_movie_ratings_user_id ON public.movie_ratings USING btree (user_id);

CREATE INDEX idx_movies_genre ON public.movies USING btree (genre);

CREATE INDEX idx_movies_genre_trgm ON public.movies USING gin (genre public.gin_trgm_ops);

CREATE INDEX idx_movies_source_key ON public.movies USING btree (source_key);

CREATE UNIQUE INDEX idx_movies_source_key_unique ON public.movies USING btree (source_key) WHERE (source_key IS NOT NULL);

CREATE INDEX idx_movies_title_lower ON public.movies USING btree (lower(title));

CREATE INDEX idx_movies_title_trgm ON public.movies USING gin (title public.gin_trgm_ops);

CREATE INDEX idx_movies_year ON public.movies USING btree (year);

CREATE INDEX idx_tv_show_ratings_user_id ON public.tv_show_ratings USING btree (user_id);

CREATE INDEX idx_tv_shows_genre ON public.tv_shows USING btree (genre);

CREATE INDEX idx_tv_shows_genre_trgm ON public.tv_shows USING gin (genre public.gin_trgm_ops);

CREATE INDEX idx_tv_shows_source_key ON public.tv_shows USING btree (source_key);

CREATE UNIQUE INDEX idx_tv_shows_source_key_unique ON public.tv_shows USING btree (source_key) WHERE (source_key IS NOT NULL);

CREATE INDEX idx_tv_shows_title_lower ON public.tv_shows USING btree (lower(title));

CREATE INDEX idx_tv_shows_title_trgm ON public.tv_shows USING gin (title public.gin_trgm_ops);

CREATE INDEX idx_tv_shows_year ON public.tv_shows USING btree (year);

CREATE INDEX idx_watchlist_user_id ON public.watchlist USING btree (user_id);

CREATE INDEX idx_watchlist_user_media ON public.watchlist USING btree (user_id, media_type, status);

CREATE UNIQUE INDEX media_list_collaborators_list_id_user_id_key ON public.media_list_collaborators USING btree (list_id, user_id);

CREATE UNIQUE INDEX media_list_collaborators_pkey ON public.media_list_collaborators USING btree (id);

CREATE UNIQUE INDEX media_list_items_list_id_media_type_media_id_key ON public.media_list_items USING btree (list_id, media_type, media_id);

CREATE UNIQUE INDEX media_list_items_pkey ON public.media_list_items USING btree (id);

CREATE UNIQUE INDEX media_list_votes_list_item_id_user_id_key ON public.media_list_votes USING btree (list_item_id, user_id);

CREATE UNIQUE INDEX media_list_votes_pkey ON public.media_list_votes USING btree (id);

CREATE UNIQUE INDEX media_lists_pkey ON public.media_lists USING btree (id);

CREATE UNIQUE INDEX media_lists_share_code_key ON public.media_lists USING btree (share_code);

CREATE UNIQUE INDEX media_requests_pkey ON public.media_requests USING btree (id);

CREATE UNIQUE INDEX movie_ratings_pkey ON public.movie_ratings USING btree (id);

CREATE UNIQUE INDEX movie_ratings_user_id_media_id_key ON public.movie_ratings USING btree (user_id, media_id);

CREATE UNIQUE INDEX movies_external_id_key ON public.movies USING btree (external_id) WHERE (external_id IS NOT NULL);

CREATE UNIQUE INDEX movies_external_id_unique ON public.movies USING btree (external_id);

CREATE UNIQUE INDEX movies_pkey ON public.movies USING btree (id);

CREATE UNIQUE INDEX movies_source_key_unique ON public.movies USING btree (source_key);

CREATE UNIQUE INDEX profiles_email_key ON public.profiles USING btree (email);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX profiles_username_key ON public.profiles USING btree (username);

CREATE UNIQUE INDEX todos_pkey ON public.todos USING btree (id);

CREATE UNIQUE INDEX tv_show_ratings_pkey ON public.tv_show_ratings USING btree (id);

CREATE UNIQUE INDEX tv_show_ratings_user_id_media_id_key ON public.tv_show_ratings USING btree (user_id, media_id);

CREATE UNIQUE INDEX tv_shows_external_id_key ON public.tv_shows USING btree (external_id) WHERE (external_id IS NOT NULL);

CREATE UNIQUE INDEX tv_shows_external_id_unique ON public.tv_shows USING btree (external_id);

CREATE UNIQUE INDEX tv_shows_pkey ON public.tv_shows USING btree (id);

CREATE UNIQUE INDEX tv_shows_source_key_unique ON public.tv_shows USING btree (source_key);

CREATE UNIQUE INDEX watchlist_pkey ON public.watchlist USING btree (id);

CREATE UNIQUE INDEX watchlist_user_id_media_type_media_id_key ON public.watchlist USING btree (user_id, media_type, media_id);

alter table "public"."book_ratings" add constraint "book_ratings_pkey" PRIMARY KEY using index "book_ratings_pkey";

alter table "public"."books" add constraint "books_pkey" PRIMARY KEY using index "books_pkey";

alter table "public"."chat_logs" add constraint "chat_logs_pkey" PRIMARY KEY using index "chat_logs_pkey";

alter table "public"."media_list_collaborators" add constraint "media_list_collaborators_pkey" PRIMARY KEY using index "media_list_collaborators_pkey";

alter table "public"."media_list_items" add constraint "media_list_items_pkey" PRIMARY KEY using index "media_list_items_pkey";

alter table "public"."media_list_votes" add constraint "media_list_votes_pkey" PRIMARY KEY using index "media_list_votes_pkey";

alter table "public"."media_lists" add constraint "media_lists_pkey" PRIMARY KEY using index "media_lists_pkey";

alter table "public"."media_requests" add constraint "media_requests_pkey" PRIMARY KEY using index "media_requests_pkey";

alter table "public"."movie_ratings" add constraint "movie_ratings_pkey" PRIMARY KEY using index "movie_ratings_pkey";

alter table "public"."movies" add constraint "movies_pkey" PRIMARY KEY using index "movies_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."todos" add constraint "todos_pkey" PRIMARY KEY using index "todos_pkey";

alter table "public"."tv_show_ratings" add constraint "tv_show_ratings_pkey" PRIMARY KEY using index "tv_show_ratings_pkey";

alter table "public"."tv_shows" add constraint "tv_shows_pkey" PRIMARY KEY using index "tv_shows_pkey";

alter table "public"."watchlist" add constraint "watchlist_pkey" PRIMARY KEY using index "watchlist_pkey";

alter table "public"."book_ratings" add constraint "book_ratings_characters_check" CHECK (((characters >= 1) AND (characters <= 6))) not valid;

alter table "public"."book_ratings" validate constraint "book_ratings_characters_check";

alter table "public"."book_ratings" add constraint "book_ratings_originality_check" CHECK (((originality >= 1) AND (originality <= 5))) not valid;

alter table "public"."book_ratings" validate constraint "book_ratings_originality_check";

alter table "public"."book_ratings" add constraint "book_ratings_pacing_check" CHECK (((pacing >= 1) AND (pacing <= 5))) not valid;

alter table "public"."book_ratings" validate constraint "book_ratings_pacing_check";

alter table "public"."book_ratings" add constraint "book_ratings_plot_check" CHECK (((plot >= 1) AND (plot <= 5))) not valid;

alter table "public"."book_ratings" validate constraint "book_ratings_plot_check";

alter table "public"."book_ratings" add constraint "book_ratings_prose_check" CHECK (((prose >= 1) AND (prose <= 5))) not valid;

alter table "public"."book_ratings" validate constraint "book_ratings_prose_check";

alter table "public"."book_ratings" add constraint "book_ratings_resonance_check" CHECK (((resonance >= 1) AND (resonance <= 6))) not valid;

alter table "public"."book_ratings" validate constraint "book_ratings_resonance_check";

alter table "public"."book_ratings" add constraint "book_ratings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."book_ratings" validate constraint "book_ratings_user_id_fkey";

alter table "public"."book_ratings" add constraint "book_ratings_user_id_media_id_key" UNIQUE using index "book_ratings_user_id_media_id_key";

alter table "public"."books" add constraint "books_external_id_key" UNIQUE using index "books_external_id_key";

alter table "public"."books" add constraint "books_source_key_key" UNIQUE using index "books_source_key_key";

alter table "public"."chat_logs" add constraint "chat_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."chat_logs" validate constraint "chat_logs_user_id_fkey";

alter table "public"."media_list_collaborators" add constraint "media_list_collaborators_invited_by_user_id_fkey" FOREIGN KEY (invited_by_user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."media_list_collaborators" validate constraint "media_list_collaborators_invited_by_user_id_fkey";

alter table "public"."media_list_collaborators" add constraint "media_list_collaborators_list_id_fkey" FOREIGN KEY (list_id) REFERENCES public.media_lists(id) ON DELETE CASCADE not valid;

alter table "public"."media_list_collaborators" validate constraint "media_list_collaborators_list_id_fkey";

alter table "public"."media_list_collaborators" add constraint "media_list_collaborators_list_id_user_id_key" UNIQUE using index "media_list_collaborators_list_id_user_id_key";

alter table "public"."media_list_collaborators" add constraint "media_list_collaborators_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."media_list_collaborators" validate constraint "media_list_collaborators_user_id_fkey";

alter table "public"."media_list_items" add constraint "media_list_items_list_id_fkey" FOREIGN KEY (list_id) REFERENCES public.media_lists(id) ON DELETE CASCADE not valid;

alter table "public"."media_list_items" validate constraint "media_list_items_list_id_fkey";

alter table "public"."media_list_items" add constraint "media_list_items_list_id_media_type_media_id_key" UNIQUE using index "media_list_items_list_id_media_type_media_id_key";

alter table "public"."media_list_items" add constraint "media_list_items_media_type_check" CHECK ((media_type = ANY (ARRAY['movie'::text, 'tv_show'::text, 'book'::text]))) not valid;

alter table "public"."media_list_items" validate constraint "media_list_items_media_type_check";

alter table "public"."media_list_votes" add constraint "media_list_votes_list_item_id_fkey" FOREIGN KEY (list_item_id) REFERENCES public.media_list_items(id) ON DELETE CASCADE not valid;

alter table "public"."media_list_votes" validate constraint "media_list_votes_list_item_id_fkey";

alter table "public"."media_list_votes" add constraint "media_list_votes_list_item_id_user_id_key" UNIQUE using index "media_list_votes_list_item_id_user_id_key";

alter table "public"."media_list_votes" add constraint "media_list_votes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."media_list_votes" validate constraint "media_list_votes_user_id_fkey";

alter table "public"."media_list_votes" add constraint "media_list_votes_value_check" CHECK ((value = ANY (ARRAY['-1'::integer, 1]))) not valid;

alter table "public"."media_list_votes" validate constraint "media_list_votes_value_check";

alter table "public"."media_lists" add constraint "media_lists_share_code_key" UNIQUE using index "media_lists_share_code_key";

alter table "public"."media_lists" add constraint "media_lists_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."media_lists" validate constraint "media_lists_user_id_fkey";

alter table "public"."media_requests" add constraint "media_requests_media_type_check" CHECK ((media_type = ANY (ARRAY['movie'::text, 'tv_show'::text, 'book'::text]))) not valid;

alter table "public"."media_requests" validate constraint "media_requests_media_type_check";

alter table "public"."media_requests" add constraint "media_requests_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text]))) not valid;

alter table "public"."media_requests" validate constraint "media_requests_status_check";

alter table "public"."media_requests" add constraint "media_requests_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."media_requests" validate constraint "media_requests_user_id_fkey";

alter table "public"."movie_ratings" add constraint "movie_ratings_acting_check" CHECK (((acting >= 1) AND (acting <= 5))) not valid;

alter table "public"."movie_ratings" validate constraint "movie_ratings_acting_check";

alter table "public"."movie_ratings" add constraint "movie_ratings_cinematography_check" CHECK (((cinematography >= 1) AND (cinematography <= 5))) not valid;

alter table "public"."movie_ratings" validate constraint "movie_ratings_cinematography_check";

alter table "public"."movie_ratings" add constraint "movie_ratings_originality_check" CHECK (((originality >= 1) AND (originality <= 5))) not valid;

alter table "public"."movie_ratings" validate constraint "movie_ratings_originality_check";

alter table "public"."movie_ratings" add constraint "movie_ratings_pacing_check" CHECK (((pacing >= 1) AND (pacing <= 5))) not valid;

alter table "public"."movie_ratings" validate constraint "movie_ratings_pacing_check";

alter table "public"."movie_ratings" add constraint "movie_ratings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."movie_ratings" validate constraint "movie_ratings_user_id_fkey";

alter table "public"."movie_ratings" add constraint "movie_ratings_user_id_media_id_key" UNIQUE using index "movie_ratings_user_id_media_id_key";

alter table "public"."movie_ratings" add constraint "movie_ratings_writing_check" CHECK (((writing >= 1) AND (writing <= 5))) not valid;

alter table "public"."movie_ratings" validate constraint "movie_ratings_writing_check";

alter table "public"."profiles" add constraint "profiles_email_key" UNIQUE using index "profiles_email_key";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_username_key" UNIQUE using index "profiles_username_key";

alter table "public"."tv_show_ratings" add constraint "tv_show_ratings_acting_check" CHECK (((acting >= 1) AND (acting <= 6))) not valid;

alter table "public"."tv_show_ratings" validate constraint "tv_show_ratings_acting_check";

alter table "public"."tv_show_ratings" add constraint "tv_show_ratings_cinematography_check" CHECK (((cinematography >= 1) AND (cinematography <= 5))) not valid;

alter table "public"."tv_show_ratings" validate constraint "tv_show_ratings_cinematography_check";

alter table "public"."tv_show_ratings" add constraint "tv_show_ratings_originality_check" CHECK (((originality >= 1) AND (originality <= 5))) not valid;

alter table "public"."tv_show_ratings" validate constraint "tv_show_ratings_originality_check";

alter table "public"."tv_show_ratings" add constraint "tv_show_ratings_pacing_check" CHECK (((pacing >= 1) AND (pacing <= 5))) not valid;

alter table "public"."tv_show_ratings" validate constraint "tv_show_ratings_pacing_check";

alter table "public"."tv_show_ratings" add constraint "tv_show_ratings_premise_check" CHECK (((premise >= 1) AND (premise <= 5))) not valid;

alter table "public"."tv_show_ratings" validate constraint "tv_show_ratings_premise_check";

alter table "public"."tv_show_ratings" add constraint "tv_show_ratings_resonance_check" CHECK (((resonance >= 1) AND (resonance <= 6))) not valid;

alter table "public"."tv_show_ratings" validate constraint "tv_show_ratings_resonance_check";

alter table "public"."tv_show_ratings" add constraint "tv_show_ratings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."tv_show_ratings" validate constraint "tv_show_ratings_user_id_fkey";

alter table "public"."tv_show_ratings" add constraint "tv_show_ratings_user_id_media_id_key" UNIQUE using index "tv_show_ratings_user_id_media_id_key";

alter table "public"."tv_show_ratings" add constraint "tv_show_ratings_writing_check" CHECK (((writing >= 1) AND (writing <= 6))) not valid;

alter table "public"."tv_show_ratings" validate constraint "tv_show_ratings_writing_check";

alter table "public"."watchlist" add constraint "watchlist_media_type_check" CHECK ((media_type = ANY (ARRAY['movie'::text, 'tv_show'::text, 'book'::text]))) not valid;

alter table "public"."watchlist" validate constraint "watchlist_media_type_check";

alter table "public"."watchlist" add constraint "watchlist_status_check" CHECK ((status = ANY (ARRAY['plan_to_watch'::text, 'watching'::text, 'watched'::text, 'plan_to_read'::text, 'reading'::text, 'read'::text]))) not valid;

alter table "public"."watchlist" validate constraint "watchlist_status_check";

alter table "public"."watchlist" add constraint "watchlist_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."watchlist" validate constraint "watchlist_user_id_fkey";

alter table "public"."watchlist" add constraint "watchlist_user_id_media_type_media_id_key" UNIQUE using index "watchlist_user_id_media_type_media_id_key";

set check_function_bodies = off;

create or replace view "public"."book_genres" as  SELECT DISTINCT TRIM(BOTH FROM split_genre.genre_value) AS genre
   FROM (public.books
     CROSS JOIN LATERAL regexp_split_to_table(COALESCE(books.genre, ''::text), ','::text) split_genre(genre_value))
  WHERE (TRIM(BOTH FROM split_genre.genre_value) <> ''::text);


CREATE OR REPLACE FUNCTION public.handle_auth_user_changed()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.profiles (id, email, username, bio, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(
      new.raw_user_meta_data ->> 'username',
      split_part(new.email, '@', 1),
      'media-fan'
    ),
    coalesce(new.raw_user_meta_data ->> 'bio', ''),
    nullif(new.raw_user_meta_data ->> 'avatar_url', '')
  )
  on conflict (id) do update
  set
    email = excluded.email,
    username = coalesce(public.profiles.username, excluded.username),
    bio = coalesce(public.profiles.bio, excluded.bio),
    avatar_url = coalesce(public.profiles.avatar_url, excluded.avatar_url);

  return new;
end;
$function$
;

create or replace view "public"."movie_genres" as  SELECT DISTINCT TRIM(BOTH FROM split_genre.genre_value) AS genre
   FROM (public.movies
     CROSS JOIN LATERAL regexp_split_to_table(COALESCE(movies.genre, ''::text), ','::text) split_genre(genre_value))
  WHERE (TRIM(BOTH FROM split_genre.genre_value) <> ''::text);


CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;

create or replace view "public"."tv_show_genres" as  SELECT DISTINCT TRIM(BOTH FROM split_genre.genre_value) AS genre
   FROM (public.tv_shows
     CROSS JOIN LATERAL regexp_split_to_table(COALESCE(tv_shows.genre, ''::text), ','::text) split_genre(genre_value))
  WHERE (TRIM(BOTH FROM split_genre.genre_value) <> ''::text);


grant delete on table "public"."book_ratings" to "anon";

grant insert on table "public"."book_ratings" to "anon";

grant references on table "public"."book_ratings" to "anon";

grant select on table "public"."book_ratings" to "anon";

grant trigger on table "public"."book_ratings" to "anon";

grant truncate on table "public"."book_ratings" to "anon";

grant update on table "public"."book_ratings" to "anon";

grant delete on table "public"."book_ratings" to "authenticated";

grant insert on table "public"."book_ratings" to "authenticated";

grant references on table "public"."book_ratings" to "authenticated";

grant select on table "public"."book_ratings" to "authenticated";

grant trigger on table "public"."book_ratings" to "authenticated";

grant truncate on table "public"."book_ratings" to "authenticated";

grant update on table "public"."book_ratings" to "authenticated";

grant delete on table "public"."book_ratings" to "service_role";

grant insert on table "public"."book_ratings" to "service_role";

grant references on table "public"."book_ratings" to "service_role";

grant select on table "public"."book_ratings" to "service_role";

grant trigger on table "public"."book_ratings" to "service_role";

grant truncate on table "public"."book_ratings" to "service_role";

grant update on table "public"."book_ratings" to "service_role";

grant delete on table "public"."books" to "anon";

grant insert on table "public"."books" to "anon";

grant references on table "public"."books" to "anon";

grant select on table "public"."books" to "anon";

grant trigger on table "public"."books" to "anon";

grant truncate on table "public"."books" to "anon";

grant update on table "public"."books" to "anon";

grant delete on table "public"."books" to "authenticated";

grant insert on table "public"."books" to "authenticated";

grant references on table "public"."books" to "authenticated";

grant select on table "public"."books" to "authenticated";

grant trigger on table "public"."books" to "authenticated";

grant truncate on table "public"."books" to "authenticated";

grant update on table "public"."books" to "authenticated";

grant delete on table "public"."books" to "service_role";

grant insert on table "public"."books" to "service_role";

grant references on table "public"."books" to "service_role";

grant select on table "public"."books" to "service_role";

grant trigger on table "public"."books" to "service_role";

grant truncate on table "public"."books" to "service_role";

grant update on table "public"."books" to "service_role";

grant delete on table "public"."chat_logs" to "anon";

grant insert on table "public"."chat_logs" to "anon";

grant references on table "public"."chat_logs" to "anon";

grant select on table "public"."chat_logs" to "anon";

grant trigger on table "public"."chat_logs" to "anon";

grant truncate on table "public"."chat_logs" to "anon";

grant update on table "public"."chat_logs" to "anon";

grant delete on table "public"."chat_logs" to "authenticated";

grant insert on table "public"."chat_logs" to "authenticated";

grant references on table "public"."chat_logs" to "authenticated";

grant select on table "public"."chat_logs" to "authenticated";

grant trigger on table "public"."chat_logs" to "authenticated";

grant truncate on table "public"."chat_logs" to "authenticated";

grant update on table "public"."chat_logs" to "authenticated";

grant delete on table "public"."chat_logs" to "service_role";

grant insert on table "public"."chat_logs" to "service_role";

grant references on table "public"."chat_logs" to "service_role";

grant select on table "public"."chat_logs" to "service_role";

grant trigger on table "public"."chat_logs" to "service_role";

grant truncate on table "public"."chat_logs" to "service_role";

grant update on table "public"."chat_logs" to "service_role";

grant delete on table "public"."media_list_collaborators" to "anon";

grant insert on table "public"."media_list_collaborators" to "anon";

grant references on table "public"."media_list_collaborators" to "anon";

grant select on table "public"."media_list_collaborators" to "anon";

grant trigger on table "public"."media_list_collaborators" to "anon";

grant truncate on table "public"."media_list_collaborators" to "anon";

grant update on table "public"."media_list_collaborators" to "anon";

grant delete on table "public"."media_list_collaborators" to "authenticated";

grant insert on table "public"."media_list_collaborators" to "authenticated";

grant references on table "public"."media_list_collaborators" to "authenticated";

grant select on table "public"."media_list_collaborators" to "authenticated";

grant trigger on table "public"."media_list_collaborators" to "authenticated";

grant truncate on table "public"."media_list_collaborators" to "authenticated";

grant update on table "public"."media_list_collaborators" to "authenticated";

grant delete on table "public"."media_list_collaborators" to "service_role";

grant insert on table "public"."media_list_collaborators" to "service_role";

grant references on table "public"."media_list_collaborators" to "service_role";

grant select on table "public"."media_list_collaborators" to "service_role";

grant trigger on table "public"."media_list_collaborators" to "service_role";

grant truncate on table "public"."media_list_collaborators" to "service_role";

grant update on table "public"."media_list_collaborators" to "service_role";

grant delete on table "public"."media_list_items" to "anon";

grant insert on table "public"."media_list_items" to "anon";

grant references on table "public"."media_list_items" to "anon";

grant select on table "public"."media_list_items" to "anon";

grant trigger on table "public"."media_list_items" to "anon";

grant truncate on table "public"."media_list_items" to "anon";

grant update on table "public"."media_list_items" to "anon";

grant delete on table "public"."media_list_items" to "authenticated";

grant insert on table "public"."media_list_items" to "authenticated";

grant references on table "public"."media_list_items" to "authenticated";

grant select on table "public"."media_list_items" to "authenticated";

grant trigger on table "public"."media_list_items" to "authenticated";

grant truncate on table "public"."media_list_items" to "authenticated";

grant update on table "public"."media_list_items" to "authenticated";

grant delete on table "public"."media_list_items" to "service_role";

grant insert on table "public"."media_list_items" to "service_role";

grant references on table "public"."media_list_items" to "service_role";

grant select on table "public"."media_list_items" to "service_role";

grant trigger on table "public"."media_list_items" to "service_role";

grant truncate on table "public"."media_list_items" to "service_role";

grant update on table "public"."media_list_items" to "service_role";

grant delete on table "public"."media_list_votes" to "anon";

grant insert on table "public"."media_list_votes" to "anon";

grant references on table "public"."media_list_votes" to "anon";

grant select on table "public"."media_list_votes" to "anon";

grant trigger on table "public"."media_list_votes" to "anon";

grant truncate on table "public"."media_list_votes" to "anon";

grant update on table "public"."media_list_votes" to "anon";

grant delete on table "public"."media_list_votes" to "authenticated";

grant insert on table "public"."media_list_votes" to "authenticated";

grant references on table "public"."media_list_votes" to "authenticated";

grant select on table "public"."media_list_votes" to "authenticated";

grant trigger on table "public"."media_list_votes" to "authenticated";

grant truncate on table "public"."media_list_votes" to "authenticated";

grant update on table "public"."media_list_votes" to "authenticated";

grant delete on table "public"."media_list_votes" to "service_role";

grant insert on table "public"."media_list_votes" to "service_role";

grant references on table "public"."media_list_votes" to "service_role";

grant select on table "public"."media_list_votes" to "service_role";

grant trigger on table "public"."media_list_votes" to "service_role";

grant truncate on table "public"."media_list_votes" to "service_role";

grant update on table "public"."media_list_votes" to "service_role";

grant delete on table "public"."media_lists" to "anon";

grant insert on table "public"."media_lists" to "anon";

grant references on table "public"."media_lists" to "anon";

grant select on table "public"."media_lists" to "anon";

grant trigger on table "public"."media_lists" to "anon";

grant truncate on table "public"."media_lists" to "anon";

grant update on table "public"."media_lists" to "anon";

grant delete on table "public"."media_lists" to "authenticated";

grant insert on table "public"."media_lists" to "authenticated";

grant references on table "public"."media_lists" to "authenticated";

grant select on table "public"."media_lists" to "authenticated";

grant trigger on table "public"."media_lists" to "authenticated";

grant truncate on table "public"."media_lists" to "authenticated";

grant update on table "public"."media_lists" to "authenticated";

grant delete on table "public"."media_lists" to "service_role";

grant insert on table "public"."media_lists" to "service_role";

grant references on table "public"."media_lists" to "service_role";

grant select on table "public"."media_lists" to "service_role";

grant trigger on table "public"."media_lists" to "service_role";

grant truncate on table "public"."media_lists" to "service_role";

grant update on table "public"."media_lists" to "service_role";

grant delete on table "public"."media_requests" to "anon";

grant insert on table "public"."media_requests" to "anon";

grant references on table "public"."media_requests" to "anon";

grant select on table "public"."media_requests" to "anon";

grant trigger on table "public"."media_requests" to "anon";

grant truncate on table "public"."media_requests" to "anon";

grant update on table "public"."media_requests" to "anon";

grant delete on table "public"."media_requests" to "authenticated";

grant insert on table "public"."media_requests" to "authenticated";

grant references on table "public"."media_requests" to "authenticated";

grant select on table "public"."media_requests" to "authenticated";

grant trigger on table "public"."media_requests" to "authenticated";

grant truncate on table "public"."media_requests" to "authenticated";

grant update on table "public"."media_requests" to "authenticated";

grant delete on table "public"."media_requests" to "service_role";

grant insert on table "public"."media_requests" to "service_role";

grant references on table "public"."media_requests" to "service_role";

grant select on table "public"."media_requests" to "service_role";

grant trigger on table "public"."media_requests" to "service_role";

grant truncate on table "public"."media_requests" to "service_role";

grant update on table "public"."media_requests" to "service_role";

grant delete on table "public"."movie_ratings" to "anon";

grant insert on table "public"."movie_ratings" to "anon";

grant references on table "public"."movie_ratings" to "anon";

grant select on table "public"."movie_ratings" to "anon";

grant trigger on table "public"."movie_ratings" to "anon";

grant truncate on table "public"."movie_ratings" to "anon";

grant update on table "public"."movie_ratings" to "anon";

grant delete on table "public"."movie_ratings" to "authenticated";

grant insert on table "public"."movie_ratings" to "authenticated";

grant references on table "public"."movie_ratings" to "authenticated";

grant select on table "public"."movie_ratings" to "authenticated";

grant trigger on table "public"."movie_ratings" to "authenticated";

grant truncate on table "public"."movie_ratings" to "authenticated";

grant update on table "public"."movie_ratings" to "authenticated";

grant delete on table "public"."movie_ratings" to "service_role";

grant insert on table "public"."movie_ratings" to "service_role";

grant references on table "public"."movie_ratings" to "service_role";

grant select on table "public"."movie_ratings" to "service_role";

grant trigger on table "public"."movie_ratings" to "service_role";

grant truncate on table "public"."movie_ratings" to "service_role";

grant update on table "public"."movie_ratings" to "service_role";

grant delete on table "public"."movies" to "anon";

grant insert on table "public"."movies" to "anon";

grant references on table "public"."movies" to "anon";

grant select on table "public"."movies" to "anon";

grant trigger on table "public"."movies" to "anon";

grant truncate on table "public"."movies" to "anon";

grant update on table "public"."movies" to "anon";

grant delete on table "public"."movies" to "authenticated";

grant insert on table "public"."movies" to "authenticated";

grant references on table "public"."movies" to "authenticated";

grant select on table "public"."movies" to "authenticated";

grant trigger on table "public"."movies" to "authenticated";

grant truncate on table "public"."movies" to "authenticated";

grant update on table "public"."movies" to "authenticated";

grant delete on table "public"."movies" to "service_role";

grant insert on table "public"."movies" to "service_role";

grant references on table "public"."movies" to "service_role";

grant select on table "public"."movies" to "service_role";

grant trigger on table "public"."movies" to "service_role";

grant truncate on table "public"."movies" to "service_role";

grant update on table "public"."movies" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."todos" to "anon";

grant insert on table "public"."todos" to "anon";

grant references on table "public"."todos" to "anon";

grant select on table "public"."todos" to "anon";

grant trigger on table "public"."todos" to "anon";

grant truncate on table "public"."todos" to "anon";

grant update on table "public"."todos" to "anon";

grant delete on table "public"."todos" to "authenticated";

grant insert on table "public"."todos" to "authenticated";

grant references on table "public"."todos" to "authenticated";

grant select on table "public"."todos" to "authenticated";

grant trigger on table "public"."todos" to "authenticated";

grant truncate on table "public"."todos" to "authenticated";

grant update on table "public"."todos" to "authenticated";

grant delete on table "public"."todos" to "service_role";

grant insert on table "public"."todos" to "service_role";

grant references on table "public"."todos" to "service_role";

grant select on table "public"."todos" to "service_role";

grant trigger on table "public"."todos" to "service_role";

grant truncate on table "public"."todos" to "service_role";

grant update on table "public"."todos" to "service_role";

grant delete on table "public"."tv_show_ratings" to "anon";

grant insert on table "public"."tv_show_ratings" to "anon";

grant references on table "public"."tv_show_ratings" to "anon";

grant select on table "public"."tv_show_ratings" to "anon";

grant trigger on table "public"."tv_show_ratings" to "anon";

grant truncate on table "public"."tv_show_ratings" to "anon";

grant update on table "public"."tv_show_ratings" to "anon";

grant delete on table "public"."tv_show_ratings" to "authenticated";

grant insert on table "public"."tv_show_ratings" to "authenticated";

grant references on table "public"."tv_show_ratings" to "authenticated";

grant select on table "public"."tv_show_ratings" to "authenticated";

grant trigger on table "public"."tv_show_ratings" to "authenticated";

grant truncate on table "public"."tv_show_ratings" to "authenticated";

grant update on table "public"."tv_show_ratings" to "authenticated";

grant delete on table "public"."tv_show_ratings" to "service_role";

grant insert on table "public"."tv_show_ratings" to "service_role";

grant references on table "public"."tv_show_ratings" to "service_role";

grant select on table "public"."tv_show_ratings" to "service_role";

grant trigger on table "public"."tv_show_ratings" to "service_role";

grant truncate on table "public"."tv_show_ratings" to "service_role";

grant update on table "public"."tv_show_ratings" to "service_role";

grant delete on table "public"."tv_shows" to "anon";

grant insert on table "public"."tv_shows" to "anon";

grant references on table "public"."tv_shows" to "anon";

grant select on table "public"."tv_shows" to "anon";

grant trigger on table "public"."tv_shows" to "anon";

grant truncate on table "public"."tv_shows" to "anon";

grant update on table "public"."tv_shows" to "anon";

grant delete on table "public"."tv_shows" to "authenticated";

grant insert on table "public"."tv_shows" to "authenticated";

grant references on table "public"."tv_shows" to "authenticated";

grant select on table "public"."tv_shows" to "authenticated";

grant trigger on table "public"."tv_shows" to "authenticated";

grant truncate on table "public"."tv_shows" to "authenticated";

grant update on table "public"."tv_shows" to "authenticated";

grant delete on table "public"."tv_shows" to "service_role";

grant insert on table "public"."tv_shows" to "service_role";

grant references on table "public"."tv_shows" to "service_role";

grant select on table "public"."tv_shows" to "service_role";

grant trigger on table "public"."tv_shows" to "service_role";

grant truncate on table "public"."tv_shows" to "service_role";

grant update on table "public"."tv_shows" to "service_role";

grant delete on table "public"."watchlist" to "anon";

grant insert on table "public"."watchlist" to "anon";

grant references on table "public"."watchlist" to "anon";

grant select on table "public"."watchlist" to "anon";

grant trigger on table "public"."watchlist" to "anon";

grant truncate on table "public"."watchlist" to "anon";

grant update on table "public"."watchlist" to "anon";

grant delete on table "public"."watchlist" to "authenticated";

grant insert on table "public"."watchlist" to "authenticated";

grant references on table "public"."watchlist" to "authenticated";

grant select on table "public"."watchlist" to "authenticated";

grant trigger on table "public"."watchlist" to "authenticated";

grant truncate on table "public"."watchlist" to "authenticated";

grant update on table "public"."watchlist" to "authenticated";

grant delete on table "public"."watchlist" to "service_role";

grant insert on table "public"."watchlist" to "service_role";

grant references on table "public"."watchlist" to "service_role";

grant select on table "public"."watchlist" to "service_role";

grant trigger on table "public"."watchlist" to "service_role";

grant truncate on table "public"."watchlist" to "service_role";

grant update on table "public"."watchlist" to "service_role";


  create policy "book_ratings_delete_own"
  on "public"."book_ratings"
  as permissive
  for delete
  to authenticated
using ((auth.uid() = user_id));



  create policy "book_ratings_insert_own"
  on "public"."book_ratings"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



  create policy "book_ratings_select_own"
  on "public"."book_ratings"
  as permissive
  for select
  to authenticated
using ((auth.uid() = user_id));



  create policy "book_ratings_update_own"
  on "public"."book_ratings"
  as permissive
  for update
  to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "books_public_read"
  on "public"."books"
  as permissive
  for select
  to public
using (true);



  create policy "movie_ratings_delete_own"
  on "public"."movie_ratings"
  as permissive
  for delete
  to authenticated
using ((auth.uid() = user_id));



  create policy "movie_ratings_insert_own"
  on "public"."movie_ratings"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



  create policy "movie_ratings_select_own"
  on "public"."movie_ratings"
  as permissive
  for select
  to authenticated
using ((auth.uid() = user_id));



  create policy "movie_ratings_update_own"
  on "public"."movie_ratings"
  as permissive
  for update
  to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "movies_public_read"
  on "public"."movies"
  as permissive
  for select
  to public
using (true);



  create policy "profiles_insert_own"
  on "public"."profiles"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = id));



  create policy "profiles_select_own"
  on "public"."profiles"
  as permissive
  for select
  to authenticated
using ((auth.uid() = id));



  create policy "profiles_update_own"
  on "public"."profiles"
  as permissive
  for update
  to authenticated
using ((auth.uid() = id))
with check ((auth.uid() = id));



  create policy "todos_public_read"
  on "public"."todos"
  as permissive
  for select
  to public
using (true);



  create policy "tv_show_ratings_delete_own"
  on "public"."tv_show_ratings"
  as permissive
  for delete
  to authenticated
using ((auth.uid() = user_id));



  create policy "tv_show_ratings_insert_own"
  on "public"."tv_show_ratings"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



  create policy "tv_show_ratings_select_own"
  on "public"."tv_show_ratings"
  as permissive
  for select
  to authenticated
using ((auth.uid() = user_id));



  create policy "tv_show_ratings_update_own"
  on "public"."tv_show_ratings"
  as permissive
  for update
  to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "tv_public_read"
  on "public"."tv_shows"
  as permissive
  for select
  to public
using (true);



  create policy "watchlist_delete_own"
  on "public"."watchlist"
  as permissive
  for delete
  to authenticated
using ((auth.uid() = user_id));



  create policy "watchlist_insert_own"
  on "public"."watchlist"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



  create policy "watchlist_select_own"
  on "public"."watchlist"
  as permissive
  for select
  to authenticated
using ((auth.uid() = user_id));



  create policy "watchlist_update_own"
  on "public"."watchlist"
  as permissive
  for update
  to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));


CREATE TRIGGER trg_media_list_votes_set_updated_at BEFORE UPDATE ON public.media_list_votes FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_media_lists_set_updated_at BEFORE UPDATE ON public.media_lists FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_media_requests_set_updated_at BEFORE UPDATE ON public.media_requests FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_profiles_set_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER on_auth_user_changed AFTER INSERT OR UPDATE ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_auth_user_changed();


