-- ── Forums (communities, like subreddits) ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS "public"."forums" (
  "id"           bigint generated by default as identity primary key,
  "name"         text not null,
  "slug"         text not null unique,
  "description"  text not null default '',
  "icon"         text not null default '💬',
  "banner_color" text not null default '#1a1a1a',
  "creator_id"   uuid not null references auth.users(id) on delete cascade,
  "member_count" integer not null default 1,
  "created_at"   timestamp with time zone default now()
);

-- ── Forum members ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "public"."forum_members" (
  "id"        bigint generated by default as identity primary key,
  "forum_id"  bigint not null references public.forums(id) on delete cascade,
  "user_id"   uuid not null references auth.users(id) on delete cascade,
  "role"      text not null default 'member' check (role in ('member','moderator','owner')),
  "joined_at" timestamp with time zone default now(),
  unique("forum_id", "user_id")
);

-- ── Posts ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "public"."posts" (
  "id"             bigint generated by default as identity primary key,
  "forum_id"       bigint not null references public.forums(id) on delete cascade,
  "user_id"        uuid not null references auth.users(id) on delete cascade,
  "title"          text not null,
  "body"           text not null default '',
  "flair"          text,
  "tags"           text[] not null default '{}',
  "score"          integer not null default 0,
  "comment_count"  integer not null default 0,
  "is_removed"     boolean not null default false,
  "removal_reason" text,
  "is_pinned"      boolean not null default false,
  "created_at"     timestamp with time zone default now(),
  "updated_at"     timestamp with time zone default now()
);

-- ── Post votes ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "public"."post_votes" (
  "id"      bigint generated by default as identity primary key,
  "post_id" bigint not null references public.posts(id) on delete cascade,
  "user_id" uuid not null references auth.users(id) on delete cascade,
  "value"   integer not null check (value in (-1, 1)),
  unique("post_id", "user_id")
);

-- ── Comments ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "public"."comments" (
  "id"                bigint generated by default as identity primary key,
  "post_id"           bigint not null references public.posts(id) on delete cascade,
  "parent_comment_id" bigint references public.comments(id) on delete cascade,
  "user_id"           uuid not null references auth.users(id) on delete cascade,
  "body"              text not null,
  "score"             integer not null default 0,
  "is_removed"        boolean not null default false,
  "removal_reason"    text,
  "created_at"        timestamp with time zone default now()
);

-- ── Comment votes ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "public"."comment_votes" (
  "id"         bigint generated by default as identity primary key,
  "comment_id" bigint not null references public.comments(id) on delete cascade,
  "user_id"    uuid not null references auth.users(id) on delete cascade,
  "value"      integer not null check (value in (-1, 1)),
  unique("comment_id", "user_id")
);

-- ── Indexes ───────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_posts_forum_id    ON public.posts(forum_id);
CREATE INDEX IF NOT EXISTS idx_posts_user_id     ON public.posts(user_id);
CREATE INDEX IF NOT EXISTS idx_posts_created_at  ON public.posts(created_at desc);
CREATE INDEX IF NOT EXISTS idx_comments_post_id  ON public.comments(post_id);
CREATE INDEX IF NOT EXISTS idx_forum_members_uid ON public.forum_members(user_id);

-- ── RLS ───────────────────────────────────────────────────────────────────────
ALTER TABLE public.forums         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.forum_members  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_votes     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comment_votes  ENABLE ROW LEVEL SECURITY;

-- Forums: anyone can read, auth users can create
CREATE POLICY "forums_read"   ON public.forums FOR SELECT USING (true);
CREATE POLICY "forums_insert" ON public.forums FOR INSERT WITH CHECK (auth.uid() = creator_id);
CREATE POLICY "forums_update" ON public.forums FOR UPDATE USING (auth.uid() = creator_id);

-- Members
CREATE POLICY "members_read"   ON public.forum_members FOR SELECT USING (true);
CREATE POLICY "members_insert" ON public.forum_members FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "members_delete" ON public.forum_members FOR DELETE USING (auth.uid() = user_id);

-- Posts: visible unless removed, users own their posts
CREATE POLICY "posts_read"   ON public.posts FOR SELECT USING (true);
CREATE POLICY "posts_insert" ON public.posts FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "posts_update" ON public.posts FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "posts_delete" ON public.posts FOR DELETE USING (auth.uid() = user_id);

-- Post votes
CREATE POLICY "post_votes_all" ON public.post_votes FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Comments
CREATE POLICY "comments_read"   ON public.comments FOR SELECT USING (true);
CREATE POLICY "comments_insert" ON public.comments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "comments_update" ON public.comments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "comments_delete" ON public.comments FOR DELETE USING (auth.uid() = user_id);

-- Comment votes
CREATE POLICY "comment_votes_all" ON public.comment_votes FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
