alter table "public"."movies" drop constraint "movies_pkey";

drop index if exists "public"."movies_pkey";


  create table "public"."episode_progress" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "media_id" bigint not null,
    "season" integer not null,
    "episode" integer not null,
    "watched_at" timestamp with time zone default now()
      );


alter table "public"."episode_progress" enable row level security;


  create table "public"."follows" (
    "id" bigint generated by default as identity not null,
    "follower_id" uuid not null,
    "following_id" uuid not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."follows" enable row level security;

alter table "public"."movie_ratings" add column "title" text;

alter table "public"."watchlist" add column "completed_at" timestamp with time zone;

alter table "public"."watchlist" add column "current_chapter" text;

alter table "public"."watchlist" add column "current_episode" integer;

alter table "public"."watchlist" add column "current_page" integer;

alter table "public"."watchlist" add column "current_season" integer;

alter table "public"."watchlist" add column "notes" text;

alter table "public"."watchlist" add column "updated_at" timestamp with time zone;

CREATE UNIQUE INDEX episode_progress_pkey ON public.episode_progress USING btree (id);

CREATE UNIQUE INDEX episode_progress_unique ON public.episode_progress USING btree (user_id, media_id, season, episode);

CREATE UNIQUE INDEX follows_follower_id_following_id_key ON public.follows USING btree (follower_id, following_id);

CREATE UNIQUE INDEX follows_pkey ON public.follows USING btree (id);

CREATE INDEX idx_episode_progress_user_media ON public.episode_progress USING btree (user_id, media_id);

CREATE UNIQUE INDEX movie_ratings_movie_title_key ON public.movie_ratings USING btree (title);

CREATE UNIQUE INDEX movies_pkey ON public.movies USING btree (id, title);

alter table "public"."episode_progress" add constraint "episode_progress_pkey" PRIMARY KEY using index "episode_progress_pkey";

alter table "public"."follows" add constraint "follows_pkey" PRIMARY KEY using index "follows_pkey";

alter table "public"."movies" add constraint "movies_pkey" PRIMARY KEY using index "movies_pkey";

alter table "public"."episode_progress" add constraint "episode_progress_unique" UNIQUE using index "episode_progress_unique";

alter table "public"."episode_progress" add constraint "episode_progress_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."episode_progress" validate constraint "episode_progress_user_id_fkey";

alter table "public"."follows" add constraint "follows_follower_id_fkey" FOREIGN KEY (follower_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."follows" validate constraint "follows_follower_id_fkey";

alter table "public"."follows" add constraint "follows_follower_id_following_id_key" UNIQUE using index "follows_follower_id_following_id_key";

alter table "public"."follows" add constraint "follows_following_id_fkey" FOREIGN KEY (following_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."follows" validate constraint "follows_following_id_fkey";

alter table "public"."movie_ratings" add constraint "movie_ratings_movie_title_key" UNIQUE using index "movie_ratings_movie_title_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_auth_user_changed()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.profiles (id, email, username, bio, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(
      new.raw_user_meta_data ->> 'username',
      split_part(new.email, '@', 1),
      'media-fan'
    ),
    coalesce(new.raw_user_meta_data ->> 'bio', ''),
    nullif(new.raw_user_meta_data ->> 'avatar_url', '')
  )
  on conflict (id) do update
  set
    email = excluded.email,
    username = coalesce(public.profiles.username, excluded.username),
    bio = coalesce(public.profiles.bio, excluded.bio),
    avatar_url = coalesce(public.profiles.avatar_url, excluded.avatar_url);

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;

grant delete on table "public"."episode_progress" to "anon";

grant insert on table "public"."episode_progress" to "anon";

grant references on table "public"."episode_progress" to "anon";

grant select on table "public"."episode_progress" to "anon";

grant trigger on table "public"."episode_progress" to "anon";

grant truncate on table "public"."episode_progress" to "anon";

grant update on table "public"."episode_progress" to "anon";

grant delete on table "public"."episode_progress" to "authenticated";

grant insert on table "public"."episode_progress" to "authenticated";

grant references on table "public"."episode_progress" to "authenticated";

grant select on table "public"."episode_progress" to "authenticated";

grant trigger on table "public"."episode_progress" to "authenticated";

grant truncate on table "public"."episode_progress" to "authenticated";

grant update on table "public"."episode_progress" to "authenticated";

grant delete on table "public"."episode_progress" to "service_role";

grant insert on table "public"."episode_progress" to "service_role";

grant references on table "public"."episode_progress" to "service_role";

grant select on table "public"."episode_progress" to "service_role";

grant trigger on table "public"."episode_progress" to "service_role";

grant truncate on table "public"."episode_progress" to "service_role";

grant update on table "public"."episode_progress" to "service_role";

grant delete on table "public"."follows" to "anon";

grant insert on table "public"."follows" to "anon";

grant references on table "public"."follows" to "anon";

grant select on table "public"."follows" to "anon";

grant trigger on table "public"."follows" to "anon";

grant truncate on table "public"."follows" to "anon";

grant update on table "public"."follows" to "anon";

grant delete on table "public"."follows" to "authenticated";

grant insert on table "public"."follows" to "authenticated";

grant references on table "public"."follows" to "authenticated";

grant select on table "public"."follows" to "authenticated";

grant trigger on table "public"."follows" to "authenticated";

grant truncate on table "public"."follows" to "authenticated";

grant update on table "public"."follows" to "authenticated";

grant delete on table "public"."follows" to "service_role";

grant insert on table "public"."follows" to "service_role";

grant references on table "public"."follows" to "service_role";

grant select on table "public"."follows" to "service_role";

grant trigger on table "public"."follows" to "service_role";

grant truncate on table "public"."follows" to "service_role";

grant update on table "public"."follows" to "service_role";


  create policy "Users can manage their own episode progress"
  on "public"."episode_progress"
  as permissive
  for all
  to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "follows_delete"
  on "public"."follows"
  as permissive
  for delete
  to authenticated
using ((auth.uid() = follower_id));



  create policy "follows_insert"
  on "public"."follows"
  as permissive
  for insert
  to authenticated
with check (((auth.uid() = follower_id) AND (auth.uid() <> following_id)));



  create policy "follows_select"
  on "public"."follows"
  as permissive
  for select
  to authenticated
using (((auth.uid() = follower_id) OR (auth.uid() = following_id)));



