-- Continue Watching progress tracking, decoupled from the watchlist/library.
-- A user can be "in progress" on a title without it being in their library,
-- and can have library titles that were never started. Starting playback
-- writes here; adding to the library (watchlist) remains a separate,
-- explicit action.
CREATE TABLE IF NOT EXISTS "public"."continue_watching" (
  "id" bigint generated by default as identity not null,
  "user_id" uuid not null references auth.users(id) on delete cascade,
  "media_type" text not null check (media_type in ('movie', 'tv_show', 'book')),
  "media_id" bigint not null,
  "current_season" integer,
  "current_episode" integer,
  "current_page" integer,
  "current_chapter" text,
  "updated_at" timestamp with time zone not null default now(),
  constraint "continue_watching_pkey" primary key ("id"),
  constraint "continue_watching_unique" unique ("user_id", "media_type", "media_id")
);

alter table "public"."continue_watching" enable row level security;

create policy "Users can manage their own continue-watching entries"
  on "public"."continue_watching"
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_continue_watching_user ON public.continue_watching USING btree (user_id);
