-- Profile settings, server health and watch reminders.

-- ── 1. Per-profile settings ───────────────────────────────────────────
-- Free-form switches that follow a profile across devices (autoplay next
-- episode, hover previews, data saver, haptics…). Audio/subtitle language
-- keep their own columns (20261007120000).
alter table public.account_profiles
  add column if not exists settings jsonb not null default '{}'::jsonb;

-- ── 2. Server health across all titles ────────────────────────────────
-- Counts only (never who), per provider, so the player can say "usually
-- works" and flag a provider that is broadly down today. Distinct viewers,
-- so one person retrying doesn't look like an outage.
create or replace function public.stream_provider_health()
returns table (
  provider text,
  works_24h bigint,
  broken_24h bigint,
  works_7d bigint,
  broken_7d bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select r.provider,
         count(distinct r.user_id) filter (where r.works and r.updated_at > now() - interval '24 hours') as works_24h,
         count(distinct r.user_id) filter (where not r.works and r.updated_at > now() - interval '24 hours') as broken_24h,
         count(distinct (r.user_id, r.media_type, r.media_id)) filter (where r.works) as works_7d,
         count(distinct (r.user_id, r.media_type, r.media_id)) filter (where not r.works) as broken_7d
  from public.stream_reports r
  where r.updated_at > now() - interval '7 days'
  group by r.provider;
$$;

revoke execute on function public.stream_provider_health() from public, anon;
grant execute on function public.stream_provider_health() to authenticated;

-- ── 3. Watch reminders ("Remind me tonight") ──────────────────────────
-- Sent as Web Push by /api/cron/reminders (service role) and also shown
-- in-app when due, so they work even without notifications enabled.
create table if not exists public.watch_reminders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  profile_id uuid references public.account_profiles(id) on delete cascade,
  media_type text not null check (media_type in ('movie', 'tv_show', 'book')),
  media_id bigint not null,
  title text not null,
  url text not null,
  remind_at timestamptz not null,
  sent_at timestamptz,
  dismissed_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists idx_watch_reminders_due
  on public.watch_reminders (remind_at) where sent_at is null and dismissed_at is null;
create index if not exists idx_watch_reminders_user on public.watch_reminders (user_id);
alter table public.watch_reminders enable row level security;
drop policy if exists watch_reminders_own on public.watch_reminders;
create policy watch_reminders_own on public.watch_reminders
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());
