-- Admin panel: our own error log, server switches, site announcements and
-- dashboard stats. Everything admin-only is gated by public.is_admin().

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select is_admin from public.profiles where id = auth.uid()), false);
$$;
revoke execute on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;

-- ── 1. Error log (replaces a third-party tracker) ─────────────────────
-- Written only by the server (/api/ops/errors, service role, rate
-- limited); admins read and resolve them.
create table if not exists public.error_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  source text not null check (source in ('client', 'server')),
  fingerprint text not null,
  message text not null,
  stack text,
  url text,
  user_agent text,
  user_id uuid references auth.users(id) on delete set null,
  release text,
  resolved boolean not null default false
);
create index if not exists idx_error_events_recent on public.error_events (created_at desc);
create index if not exists idx_error_events_fingerprint on public.error_events (fingerprint, created_at desc);
alter table public.error_events enable row level security;
drop policy if exists error_events_admin_read on public.error_events;
create policy error_events_admin_read on public.error_events for select using (public.is_admin());
drop policy if exists error_events_admin_update on public.error_events;
create policy error_events_admin_update on public.error_events for update using (public.is_admin()) with check (public.is_admin());
drop policy if exists error_events_admin_delete on public.error_events;
create policy error_events_admin_delete on public.error_events for delete using (public.is_admin());

-- ── 2. Streaming-server switches ──────────────────────────────────────
-- An admin can take a server out of rotation for everyone (it stops being
-- offered or auto-picked) without a deploy.
create table if not exists public.server_config (
  provider text primary key,
  enabled boolean not null default true,
  note text,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);
alter table public.server_config enable row level security;
drop policy if exists server_config_read on public.server_config;
create policy server_config_read on public.server_config for select using (true);
drop policy if exists server_config_admin_write on public.server_config;
create policy server_config_admin_write on public.server_config for all using (public.is_admin()) with check (public.is_admin());

-- ── 3. Site-wide announcements (banner) ───────────────────────────────
create table if not exists public.site_announcements (
  id bigint generated by default as identity primary key,
  message text not null check (char_length(message) between 1 and 280),
  level text not null default 'info' check (level in ('info', 'warning', 'critical')),
  link_url text,
  link_label text,
  active boolean not null default true,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
alter table public.site_announcements enable row level security;
drop policy if exists site_announcements_read on public.site_announcements;
create policy site_announcements_read on public.site_announcements for select
  using (public.is_admin() or (active and starts_at <= now() and (ends_at is null or ends_at > now())));
drop policy if exists site_announcements_admin_write on public.site_announcements;
create policy site_announcements_admin_write on public.site_announcements for all using (public.is_admin()) with check (public.is_admin());

-- ── 4. Dashboard numbers ──────────────────────────────────────────────
-- One call for the Overview tab. Aggregates only; refuses non-admins.
create or replace function public.admin_stats()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if not public.is_admin() then
    raise exception 'admin only' using errcode = '42501';
  end if;

  with activity as (
    select user_id, updated_at as at from public.continue_watching where updated_at > now() - interval '30 days'
    union all
    select user_id, watched_at from public.episode_progress where watched_at > now() - interval '30 days'
    union all
    select user_id, created_at from public.movie_ratings where created_at > now() - interval '30 days'
    union all
    select user_id, created_at from public.tv_show_ratings where created_at > now() - interval '30 days'
  ),
  days as (
    select generate_series(current_date - 13, current_date, interval '1 day')::date as day
  ),
  top_titles as (
    select cw.media_type, cw.media_id, count(distinct cw.user_id) as viewers
    from public.continue_watching cw
    where cw.updated_at > now() - interval '7 days'
    group by 1, 2
    order by viewers desc
    limit 10
  )
  select jsonb_build_object(
    'users_total', (select count(*) from public.profiles),
    'users_new_7d', (select count(*) from public.profiles where created_at > now() - interval '7 days'),
    'users_new_30d', (select count(*) from public.profiles where created_at > now() - interval '30 days'),
    'active_24h', (select count(distinct user_id) from activity where at > now() - interval '24 hours'),
    'active_7d', (select count(distinct user_id) from activity where at > now() - interval '7 days'),
    'active_30d', (select count(distinct user_id) from activity),
    'ratings_total', (select count(*) from public.movie_ratings) + (select count(*) from public.tv_show_ratings) + (select count(*) from public.book_ratings),
    'list_total', (select count(*) from public.watchlist),
    'push_devices', (select count(*) from public.push_subscriptions),
    'reminders_pending', (select count(*) from public.watch_reminders where sent_at is null and dismissed_at is null),
    'followed_teams', (select count(*) from public.followed_teams),
    'errors_24h', (select count(*) from public.error_events where created_at > now() - interval '24 hours' and not resolved),
    'signups_by_day', (
      select jsonb_agg(jsonb_build_object('day', d.day, 'count', coalesce(p.count, 0)) order by d.day)
      from days d
      left join (select created_at::date as day, count(*) from public.profiles group by 1) p on p.day = d.day
    ),
    'active_by_day', (
      select jsonb_agg(jsonb_build_object('day', d.day, 'count', coalesce(a.count, 0)) order by d.day)
      from days d
      left join (select at::date as day, count(distinct user_id) from activity group by 1) a on a.day = d.day
    ),
    'top_titles', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'media_type', t.media_type, 'media_id', t.media_id, 'viewers', t.viewers,
        'title', coalesce(m.title, s.title), 'poster_url', coalesce(m.poster_url, s.poster_url)
      ) order by t.viewers desc), '[]'::jsonb)
      from top_titles t
      left join public.movies m on t.media_type = 'movie' and m.id = t.media_id
      left join public.tv_shows s on t.media_type = 'tv_show' and s.id = t.media_id
    )
  ) into result;
  return result;
end;
$$;
revoke execute on function public.admin_stats() from public, anon;
grant execute on function public.admin_stats() to authenticated;
