-- Episode progress tracking (which episodes a user has watched)
CREATE TABLE IF NOT EXISTS "public"."episode_progress" (
  "id" bigint generated by default as identity not null,
  "user_id" uuid not null references auth.users(id) on delete cascade,
  "media_id" bigint not null,
  "season" integer not null,
  "episode" integer not null,
  "watched_at" timestamp with time zone default now(),
  constraint "episode_progress_pkey" primary key ("id"),
  constraint "episode_progress_unique" unique ("user_id", "media_id", "season", "episode")
);

alter table "public"."episode_progress" enable row level security;

create policy "Users can manage their own episode progress"
  on "public"."episode_progress"
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Add progress tracking columns to watchlist
ALTER TABLE "public"."watchlist"
  ADD COLUMN IF NOT EXISTS "current_season" integer,
  ADD COLUMN IF NOT EXISTS "current_episode" integer,
  ADD COLUMN IF NOT EXISTS "current_page" integer,
  ADD COLUMN IF NOT EXISTS "current_chapter" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "completed_at" timestamp with time zone,
  ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_episode_progress_user_media ON public.episode_progress USING btree (user_id, media_id);
