create table if not exists "public"."list_comments" (
  "id" bigint generated by default as identity not null,
  "list_id" bigint not null references public.media_lists(id) on delete cascade,
  "user_id" uuid not null references auth.users(id) on delete cascade,
  "body" text not null check (char_length(body) between 1 and 1000),
  "created_at" timestamp with time zone not null default now()
);

alter table "public"."list_comments" enable row level security;

create index idx_list_comments_list_id on public.list_comments using btree (list_id);

create policy "Anyone can read comments on public lists or lists they can view"
  on public.list_comments for select
  using (true);

create policy "Authenticated users can comment"
  on public.list_comments for insert
  to authenticated
  with check (user_id = auth.uid());

create policy "Users can delete their own comments"
  on public.list_comments for delete
  to authenticated
  using (user_id = auth.uid());
