-- ── 1. Crowd-sourced intro / credits markers ─────────────────────────
-- Each viewer's best guess for one episode: where the intro starts/ends
-- (learned from skipping it) and where the credits start (learned from
-- moving on to the next episode). One row per viewer per episode per kind;
-- everyone reads the median once enough different viewers agree.
create table if not exists public.episode_markers (
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  media_id bigint not null,
  season integer not null,
  episode integer not null,
  kind text not null check (kind in ('intro', 'credits')),
  start_s real not null check (start_s >= 0 and start_s < 36000),
  end_s real check (end_s is null or (end_s > start_s and end_s < 36000)),
  duration_s real,
  updated_at timestamptz not null default now(),
  primary key (user_id, media_id, season, episode, kind)
);
create index if not exists episode_markers_episode_idx on public.episode_markers (media_id, season, episode);
alter table public.episode_markers enable row level security;
drop policy if exists episode_markers_own on public.episode_markers;
create policy episode_markers_own on public.episode_markers for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Medians per kind, only where at least p_min_viewers different viewers
-- agree (anyone can read the result; individual rows stay private).
-- Falls back to the show's typical intro length when this episode has no
-- intro data of its own (reported as source 'show').
create or replace function public.episode_marker_summary(
  p_media_id bigint, p_season integer, p_episode integer, p_min_viewers integer default 2
) returns table (kind text, start_s real, end_s real, viewers integer, source text)
language sql stable security definer set search_path = public as $$
  with ep as (
    select m.kind,
           percentile_cont(0.5) within group (order by m.start_s)::real as start_s,
           percentile_cont(0.5) within group (order by m.end_s)::real as end_s,
           count(distinct m.user_id)::int as viewers
    from public.episode_markers m
    where m.media_id = p_media_id and m.season = p_season and m.episode = p_episode
    group by m.kind
    having count(distinct m.user_id) >= greatest(1, p_min_viewers)
  ),
  show_intro as (
    select percentile_cont(0.5) within group (order by m.start_s)::real as start_s,
           percentile_cont(0.5) within group (order by m.end_s)::real as end_s,
           count(distinct m.user_id)::int as viewers
    from public.episode_markers m
    where m.media_id = p_media_id and m.kind = 'intro' and m.end_s is not null
    having count(distinct m.user_id) >= greatest(1, p_min_viewers) + 1
  )
  select e.kind, e.start_s, e.end_s, e.viewers, 'episode'::text from ep e
  union all
  select 'intro', s.start_s, s.end_s, s.viewers, 'show'::text from show_intro s
  where not exists (select 1 from ep where ep.kind = 'intro');
$$;
grant execute on function public.episode_marker_summary(bigint, integer, integer, integer) to anon, authenticated;

-- ── 2. Household queue: profiles send titles to each other ────────────
create table if not exists public.profile_shares (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  from_profile uuid references public.account_profiles(id) on delete cascade,
  to_profile uuid not null references public.account_profiles(id) on delete cascade,
  media_type text not null check (media_type in ('movie', 'tv_show', 'book')),
  media_id bigint not null,
  note text check (note is null or char_length(note) <= 140),
  created_at timestamptz not null default now(),
  seen_at timestamptz,
  unique (to_profile, media_type, media_id)
);
create index if not exists profile_shares_to_idx on public.profile_shares (to_profile, created_at desc);
alter table public.profile_shares enable row level security;
drop policy if exists profile_shares_own on public.profile_shares;
create policy profile_shares_own on public.profile_shares for all
  using (user_id = auth.uid()) with check (
    user_id = auth.uid()
    and exists (select 1 from public.account_profiles p where p.id = to_profile and p.account_id = auth.uid())
    and (from_profile is null or exists (select 1 from public.account_profiles p where p.id = from_profile and p.account_id = auth.uid()))
  );
