-- New-episode push alerts + "hide from recommendations".

-- One row per browser/device that opted in to notifications.
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  profile_id uuid references public.account_profiles(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_push_subscriptions_user on public.push_subscriptions(user_id);
alter table public.push_subscriptions enable row level security;
drop policy if exists push_subscriptions_own on public.push_subscriptions;
create policy push_subscriptions_own on public.push_subscriptions
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Which episode each profile was already told about (written by the cron
-- with the service role, so no client policies beyond reading your own).
create table if not exists public.push_notified (
  user_id uuid not null references auth.users(id) on delete cascade,
  profile_id uuid references public.account_profiles(id) on delete cascade,
  media_id bigint not null,
  episode_key text not null,
  sent_at timestamptz not null default now(),
  primary key (user_id, media_id, episode_key)
);
alter table public.push_notified enable row level security;
drop policy if exists push_notified_read_own on public.push_notified;
create policy push_notified_read_own on public.push_notified
  for select using (user_id = auth.uid());

-- Titles a profile asked never to see recommended again.
create table if not exists public.recommendation_hidden (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  profile_id uuid references public.account_profiles(id) on delete cascade,
  media_type text not null check (media_type in ('movie', 'tv_show', 'book')),
  media_id bigint not null,
  created_at timestamptz not null default now()
);
create unique index if not exists idx_recommendation_hidden_unique
  on public.recommendation_hidden (user_id, coalesce(profile_id, '00000000-0000-0000-0000-000000000000'::uuid), media_type, media_id);
alter table public.recommendation_hidden enable row level security;
drop policy if exists recommendation_hidden_own on public.recommendation_hidden;
create policy recommendation_hidden_own on public.recommendation_hidden
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());
