const { Pool } = require('pg');

const connectionString = process.env.SUPABASE_DB_URL || process.env.DATABASE_URL;

const pool = connectionString
  ? new Pool({
      connectionString,
      ssl: { rejectUnauthorized: false },
      application_name: 'project-3-dev-lab',
      max: 3,
    })
  : null;

const DEFAULT_PROMPT_PROFILES = [
  {
    intent: 'general',
    label: 'General',
    description: 'Balanced everyday assistant behavior for broad questions.',
    systemPrompt: 'Answer in a warm, natural voice. Prefer short paragraphs, stay grounded in the provided catalog and knowledge base, and do not use markdown bullets unless the user asks for a list.',
    temperature: 0.45,
    maxTitles: 5,
  },
  {
    intent: 'factual',
    label: 'Factual Lookup',
    description: 'Direct answers for cast, release, runtime, and title lookups.',
    systemPrompt: 'Answer directly and accurately. Lead with the answer, keep the wording compact, and only mention supporting context that helps the user verify the fact.',
    temperature: 0.2,
    maxTitles: 3,
  },
  {
    intent: 'thematic',
    label: 'Explanation',
    description: 'Interpretive answers about themes, comparisons, and analysis.',
    systemPrompt: 'Explain ideas clearly and conversationally. Focus on meaning, themes, and comparisons, and connect the answer back to the user question instead of sounding academic.',
    temperature: 0.4,
    maxTitles: 4,
  },
  {
    intent: 'recommendation',
    label: 'Recommendation',
    description: 'Recommendation mode for shortlist-style answers.',
    systemPrompt: 'Recommend only the strongest matches. Keep the answer human and specific, mention why each suggestion fits, and avoid dumping a long catalog.',
    temperature: 0.55,
    maxTitles: 5,
  },
  {
    intent: 'creative',
    label: 'Creative',
    description: 'Creative responses such as pitches, rewrites, and alternate versions.',
    systemPrompt: 'Be imaginative while still respecting the supplied context. Use an engaging voice, but keep the output readable and avoid heavy markdown formatting.',
    temperature: 0.75,
    maxTitles: 4,
  },
];

let schemaReadyPromise = null;

function ensurePool() {
  if (!pool) {
    throw new Error('Dev lab storage is unavailable. Set SUPABASE_DB_URL (or DATABASE_URL) for server-side Supabase access.');
  }

  return pool;
}

async function query(text, params = []) {
  const db = ensurePool();
  return db.query(text, params);
}

async function ensureDevLabSchema() {
  if (!schemaReadyPromise) {
    schemaReadyPromise = (async () => {
      await query(`
        create extension if not exists pgcrypto;

        create table if not exists public.chatbot_knowledge_documents (
          id uuid primary key default gen_random_uuid(),
          title text not null,
          source_type text not null,
          media_type text,
          source_url text,
          source_label text,
          tags text[] not null default '{}',
          content text not null,
          summary text,
          metadata jsonb not null default '{}'::jsonb,
          created_at timestamptz not null default now(),
          updated_at timestamptz not null default now()
        );

        create index if not exists idx_chatbot_knowledge_documents_title
          on public.chatbot_knowledge_documents (lower(title));
        create index if not exists idx_chatbot_knowledge_documents_source_type
          on public.chatbot_knowledge_documents (source_type);
        create index if not exists idx_chatbot_knowledge_documents_tags
          on public.chatbot_knowledge_documents using gin (tags);

        create table if not exists public.chatbot_prompt_profiles (
          intent text primary key,
          label text not null,
          description text,
          system_prompt text not null,
          temperature real not null default 0.4,
          max_titles integer not null default 5,
          updated_at timestamptz not null default now()
        );

        create table if not exists public.chatbot_eval_cases (
          id bigint generated by default as identity primary key,
          label text not null,
          question text not null,
          expected_intent text,
          expected_phrases text[] not null default '{}',
          forbidden_phrases text[] not null default '{}',
          notes text,
          created_at timestamptz not null default now(),
          updated_at timestamptz not null default now()
        );

        create table if not exists public.chatbot_eval_runs (
          id bigint generated by default as identity primary key,
          case_id bigint references public.chatbot_eval_cases(id) on delete set null,
          label text,
          question text not null,
          selected_intent text,
          intent_match boolean not null default true,
          passed boolean not null default false,
          expected_hits text[] not null default '{}',
          missing_expected text[] not null default '{}',
          forbidden_hits text[] not null default '{}',
          response_text text not null,
          system_prompt text,
          latency_ms integer,
          created_at timestamptz not null default now()
        );

        create index if not exists idx_chatbot_eval_runs_created_at
          on public.chatbot_eval_runs (created_at desc);
      `);

      for (const profile of DEFAULT_PROMPT_PROFILES) {
        await query(
          `
            insert into public.chatbot_prompt_profiles (
              intent,
              label,
              description,
              system_prompt,
              temperature,
              max_titles
            )
            values ($1, $2, $3, $4, $5, $6)
            on conflict (intent) do nothing
          `,
          [
            profile.intent,
            profile.label,
            profile.description,
            profile.systemPrompt,
            profile.temperature,
            profile.maxTitles,
          ]
        );
      }
    })().catch((error) => {
      schemaReadyPromise = null;
      throw error;
    });
  }

  return schemaReadyPromise;
}

function normalizeTagList(tags) {
  if (Array.isArray(tags)) {
    return [...new Set(tags.map((tag) => String(tag || '').trim()).filter(Boolean))];
  }

  return String(tags || '')
    .split(/[,\n]/)
    .map((tag) => tag.trim())
    .filter(Boolean)
    .filter((tag, index, values) => values.indexOf(tag) === index);
}

async function getDashboardSnapshot() {
  await ensureDevLabSchema();

  const [counts, prompts, knowledge, evalCases, evalRuns] = await Promise.all([
    query(`
      select
        (select count(*)::int from public.movies where source_key is not null) as movie_count,
        (select count(*)::int from public.tv_shows where source_key is not null) as tv_count,
        (select count(*)::int from public.books where source_key is not null) as book_count,
        (select count(*)::int from public.chatbot_knowledge_documents) as knowledge_count,
        (select count(*)::int from public.chatbot_eval_cases) as eval_case_count
    `),
    listPromptProfiles(),
    listKnowledgeDocuments(),
    listEvalCases(),
    listEvalRuns(),
  ]);

  return {
    counts: counts.rows[0] || {
      movie_count: 0,
      tv_count: 0,
      book_count: 0,
      knowledge_count: 0,
      eval_case_count: 0,
    },
    prompts,
    knowledge,
    evalCases,
    evalRuns,
  };
}

async function listPromptProfiles() {
  await ensureDevLabSchema();
  const result = await query(`
    select
      intent,
      label,
      description,
      system_prompt as "systemPrompt",
      temperature,
      max_titles as "maxTitles",
      updated_at as "updatedAt"
    from public.chatbot_prompt_profiles
    order by intent asc
  `);
  return result.rows;
}

async function upsertPromptProfile(profile) {
  await ensureDevLabSchema();

  const result = await query(
    `
      insert into public.chatbot_prompt_profiles (
        intent,
        label,
        description,
        system_prompt,
        temperature,
        max_titles,
        updated_at
      )
      values ($1, $2, $3, $4, $5, $6, now())
      on conflict (intent) do update
      set
        label = excluded.label,
        description = excluded.description,
        system_prompt = excluded.system_prompt,
        temperature = excluded.temperature,
        max_titles = excluded.max_titles,
        updated_at = now()
      returning
        intent,
        label,
        description,
        system_prompt as "systemPrompt",
        temperature,
        max_titles as "maxTitles",
        updated_at as "updatedAt"
    `,
    [
      String(profile.intent || '').trim(),
      String(profile.label || '').trim(),
      String(profile.description || '').trim() || null,
      String(profile.systemPrompt || '').trim(),
      Number(profile.temperature) || 0.4,
      Math.max(1, Math.min(12, Number(profile.maxTitles) || 5)),
    ]
  );

  return result.rows[0];
}

async function listKnowledgeDocuments(limit = 20) {
  await ensureDevLabSchema();
  const result = await query(
    `
      select
        id,
        title,
        source_type as "sourceType",
        media_type as "mediaType",
        source_url as "sourceUrl",
        source_label as "sourceLabel",
        tags,
        left(content, 480) as excerpt,
        summary,
        metadata,
        created_at as "createdAt",
        updated_at as "updatedAt"
      from public.chatbot_knowledge_documents
      order by updated_at desc, created_at desc
      limit $1
    `,
    [Math.max(1, Math.min(100, Number(limit) || 20))]
  );
  return result.rows;
}

async function createKnowledgeDocument(document) {
  await ensureDevLabSchema();

  const result = await query(
    `
      insert into public.chatbot_knowledge_documents (
        title,
        source_type,
        media_type,
        source_url,
        source_label,
        tags,
        content,
        summary,
        metadata,
        updated_at
      )
      values ($1, $2, $3, $4, $5, $6::text[], $7, $8, $9::jsonb, now())
      returning
        id,
        title,
        source_type as "sourceType",
        media_type as "mediaType",
        source_url as "sourceUrl",
        source_label as "sourceLabel",
        tags,
        left(content, 480) as excerpt,
        summary,
        metadata,
        created_at as "createdAt",
        updated_at as "updatedAt"
    `,
    [
      String(document.title || '').trim(),
      String(document.sourceType || '').trim(),
      String(document.mediaType || '').trim() || null,
      String(document.sourceUrl || '').trim() || null,
      String(document.sourceLabel || '').trim() || null,
      normalizeTagList(document.tags),
      String(document.content || '').trim(),
      String(document.summary || '').trim() || null,
      JSON.stringify(document.metadata || {}),
    ]
  );

  return result.rows[0];
}

async function deleteKnowledgeDocument(id) {
  await ensureDevLabSchema();
  await query(`delete from public.chatbot_knowledge_documents where id = $1`, [id]);
}

async function searchKnowledgeDocuments(search, limit = 4) {
  await ensureDevLabSchema();

  const terms = String(search || '')
    .toLowerCase()
    .replace(/[^a-z0-9 ]/g, ' ')
    .split(/\s+/)
    .filter((term) => term.length > 2)
    .slice(0, 5);

  if (!terms.length) {
    return [];
  }

  const params = [];
  const clauses = terms.map((term) => {
    params.push(`%${term}%`);
    return `(
      lower(title) like $${params.length}
      or lower(content) like $${params.length}
      or lower(coalesce(summary, '')) like $${params.length}
      or lower(array_to_string(tags, ' ')) like $${params.length}
    )`;
  });

  params.push(Math.max(1, Math.min(12, Number(limit) || 4)));

  const result = await query(
    `
      select
        id,
        title,
        source_type as "sourceType",
        media_type as "mediaType",
        source_url as "sourceUrl",
        source_label as "sourceLabel",
        tags,
        left(content, 900) as excerpt,
        summary,
        metadata,
        created_at as "createdAt",
        updated_at as "updatedAt"
      from public.chatbot_knowledge_documents
      where ${clauses.join(' or ')}
      order by updated_at desc, created_at desc
      limit $${params.length}
    `,
    params
  );

  return result.rows;
}

async function listEvalCases(limit = 30) {
  await ensureDevLabSchema();
  const result = await query(
    `
      select
        id,
        label,
        question,
        expected_intent as "expectedIntent",
        expected_phrases as "expectedPhrases",
        forbidden_phrases as "forbiddenPhrases",
        notes,
        created_at as "createdAt",
        updated_at as "updatedAt"
      from public.chatbot_eval_cases
      order by updated_at desc, created_at desc
      limit $1
    `,
    [Math.max(1, Math.min(100, Number(limit) || 30))]
  );

  return result.rows;
}

async function createEvalCase(testCase) {
  await ensureDevLabSchema();

  const result = await query(
    `
      insert into public.chatbot_eval_cases (
        label,
        question,
        expected_intent,
        expected_phrases,
        forbidden_phrases,
        notes,
        updated_at
      )
      values ($1, $2, $3, $4::text[], $5::text[], $6, now())
      returning
        id,
        label,
        question,
        expected_intent as "expectedIntent",
        expected_phrases as "expectedPhrases",
        forbidden_phrases as "forbiddenPhrases",
        notes,
        created_at as "createdAt",
        updated_at as "updatedAt"
    `,
    [
      String(testCase.label || '').trim(),
      String(testCase.question || '').trim(),
      String(testCase.expectedIntent || '').trim() || null,
      normalizeTagList(testCase.expectedPhrases),
      normalizeTagList(testCase.forbiddenPhrases),
      String(testCase.notes || '').trim() || null,
    ]
  );

  return result.rows[0];
}

async function deleteEvalCase(id) {
  await ensureDevLabSchema();
  await query(`delete from public.chatbot_eval_cases where id = $1`, [Number(id)]);
}

async function createEvalRun(run) {
  await ensureDevLabSchema();

  const result = await query(
    `
      insert into public.chatbot_eval_runs (
        case_id,
        label,
        question,
        selected_intent,
        intent_match,
        passed,
        expected_hits,
        missing_expected,
        forbidden_hits,
        response_text,
        system_prompt,
        latency_ms
      )
      values ($1, $2, $3, $4, $5, $6, $7::text[], $8::text[], $9::text[], $10, $11, $12)
      returning
        id,
        case_id as "caseId",
        label,
        question,
        selected_intent as "selectedIntent",
        intent_match as "intentMatch",
        passed,
        expected_hits as "expectedHits",
        missing_expected as "missingExpected",
        forbidden_hits as "forbiddenHits",
        response_text as "responseText",
        system_prompt as "systemPrompt",
        latency_ms as "latencyMs",
        created_at as "createdAt"
    `,
    [
      run.caseId ? Number(run.caseId) : null,
      String(run.label || '').trim() || null,
      String(run.question || '').trim(),
      String(run.selectedIntent || '').trim() || null,
      Boolean(run.intentMatch),
      Boolean(run.passed),
      normalizeTagList(run.expectedHits),
      normalizeTagList(run.missingExpected),
      normalizeTagList(run.forbiddenHits),
      String(run.responseText || '').trim(),
      String(run.systemPrompt || '').trim() || null,
      Number(run.latencyMs) || null,
    ]
  );

  return result.rows[0];
}

async function listEvalRuns(limit = 20) {
  await ensureDevLabSchema();
  const result = await query(
    `
      select
        id,
        case_id as "caseId",
        label,
        question,
        selected_intent as "selectedIntent",
        intent_match as "intentMatch",
        passed,
        expected_hits as "expectedHits",
        missing_expected as "missingExpected",
        forbidden_hits as "forbiddenHits",
        response_text as "responseText",
        system_prompt as "systemPrompt",
        latency_ms as "latencyMs",
        created_at as "createdAt"
      from public.chatbot_eval_runs
      order by created_at desc
      limit $1
    `,
    [Math.max(1, Math.min(100, Number(limit) || 20))]
  );

  return result.rows;
}

module.exports = {
  ensureDevLabSchema,
  ensurePool,
  getDashboardSnapshot,
  listPromptProfiles,
  upsertPromptProfile,
  listKnowledgeDocuments,
  createKnowledgeDocument,
  deleteKnowledgeDocument,
  searchKnowledgeDocuments,
  listEvalCases,
  createEvalCase,
  deleteEvalCase,
  createEvalRun,
  listEvalRuns,
  normalizeTagList,
  query,
};
